#!/bin/sh
#Barry Kauler, LGPL 2009

#If a different modem selected, quit...
[ -h /dev/modem ] && exit

[ ! $1 ] && exit
[ "$1" != "start" ] && exit

#Wait for driver to load.
/sbin/pup_event_backend_modprobe_protect --modcheck=nozomi || exit #v432

ln -snf noz0 /dev/modem
ln -snf noz0 /dev/ttyS_NOZ0 #for pupdial probe

#the module doesn't seem to support any country setting, so...
if [ -f /etc/countryinfo ];then
 SPATTERN="s/^MODEM_COUNTRY_STRING.*/MODEM_COUNTRY_STRING=''/"
 sed -i -e "$SPATTERN" /etc/countryinfo
fi
#.../usr/sbin/gen_modem_init_string reads this variable.

###END###
