#!/bin/ash
# only detect if disc inserted

device=/dev/sr0
if [ "$1" ] ; then
	device=${1#-d} #remove leading '-d'
fi

if [ ! -b "$device" ] ; then
	exit 1
fi

eval "$(/lib/udev/cdrom_id $device)"
if [ "$ID_CDROM_MEDIA" ] ; then
	echo "disc inserted"
	exit 0 #ok
fi

if [ "$ID_CDROM" ] ; then
	if [ ! "$ID_CDROM_MEDIA" ] ; then
		echo "tray open" #pburn requires this
	fi
fi

exit 255 #error
