#!/bin/sh
#110505 support sudo for non-root user.
#140622 shinobar avoid freeze on a virtual terminal

for i in $@ ; do
	case $i in
		debug) echo > /tmp/debugshutdown ;;
		shell) echo > /tmp/shutdownshell ;;
	esac
done

script=${0##*/}

. /etc/rc.d/PUPSTATE
if [ "$PUPMODE" = "5" ] && [ $PPID -eq 1 ] ; then
	touch /tmp/shutdownconfig_results ; sync  #skip shutdownconfig
fi

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505

if [ "$DISPLAY" ] ; then
	case $script in
		poweroff)  exec wmpoweroff $@ ;; #avoid freeze on a virtual terminal
		reboot) exec wmreboot $@ ;;
	esac
fi

if [ "$script" = "reboot" ] ; then
	touch /tmp/is_reboot
fi

case $script in
	poweroff) /bin/busybox poweroff $@ ;;
	reboot) /bin/busybox reboot $@ ;;
	*) exit ;;
esac

### END ###
