#!/bin/ash
#this script is called from /root/.xinitrc

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@}

PS="`busybox ps`"
echo "$PS" | grep -q  ' /usr/local/pup_event/pup_event_frontend_d' || {
	if [ "$1" = "-debug" ] ; then
		exec /usr/local/pup_event/pup_event_frontend_d $@ &> /tmp/pup_event_frontend_d.log
	else
		exec /usr/local/pup_event/pup_event_frontend_d $@
	fi
}

echo "${0##*/} already running..."

###END###
