#!/bin/sh
#110505 support sudo for non-root user.
#120408 support minit

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505

/etc/rc.d/rc.shutdown

REBOOTEXE='/bin/busybox reboot'
#[ -f /sbin/minit ] && REBOOTEXE='/sbin/shutdown -r' #-r means reboot. note, shutdown is part of minit pkg.
[ -f /sbin/minit ] && REBOOTEXE='hard-reboot RESTART' #note, hard-reboot is part of minit pkg.

exec ${REBOOTEXE} #>/dev/null 2>&1
