#!/bin/sh
# update-pciids for puppy linux

#URL="http://pci-ids.ucw.cz/pci.ids"
URL="http://pci-ids.ucw.cz/v2.2/pci.ids"
URL=${URL}.bz2
FILE=${URL##*/}

mkdir -p /usr/share/hwdata
mkdir -p /usr/share/misc
wget --no-check-certificate -O /usr/share/hwdata/${FILE} $URL || exit
find /usr/share -name 'pci.ids' -delete
bunzip2 /usr/share/hwdata/${FILE} || exit
ln -sf ../../../usr/share/hwdata/pci.ids /usr/share/misc/pci.ids
ln -sf ../../usr/share/hwdata/pci.ids /usr/share/pci.ids

grep -o 'Version: .*' /usr/share/misc/pci.ids
echo "Done."

### END ###
