#!/bin/ash
#(c) Copyright Barry Kauler 2012, license GPL3 (/usr/share/doc/legal)
#call from: /usr/sbin/delayedrun, quicksetup, ...
#120331 ping -4 for ipv4, refer: http://murga-linux.com/puppy/viewtopic.php?p=616090#616090

export LANG=C

IFCONFIG="`ifconfig | grep '^[pwe]' | grep -v 'wmaster'`"
[ ! "$IFCONFIG" ] && exit 1 #no network connection.

exit 0 #success
###END###
