#!/bin/bash
# Set new current network manager/exec
# Single argument: new network exec name - sns|net-setup.sh|frisbee
#Exit code: always 0.
#200910 resolve shellcheck warnings.
#231212 Add connman support; move killing of residual manager processes to new connectwizard_switcher.

[ -z "$1" ] && exit 0
NEWEXEC="$1"

if [ -f /root/.connectwizardrc ];then
# shellcheck disable=SC1091
    . /root/.connectwizardrc #sets CURRENT_EXEC
elif grep -qw 'connman-gtk' /usr/local/bin/defaultconnect; then #231212
    CURRENT_EXEC='connman-gtk' #231212
else
    CURRENT_EXEC='connectwizard'
fi

if [ "$NEWEXEC" != "$CURRENT_EXEC" ]; then
    # kill any remaining manager processes and change setups between legacy and connman
    export CURRENT_EXEC NEWEXEC #231212
    exec connectwizard_switcher #231212
fi
exit 0
