#!/bin/sh

# timezone fixer upperer
# helper for quicksetup (and friends) and psync
# inverts the '+' or '-' for gui display because in 
# /usr/share/zoneinfo/Etc GMT[+-] are inverted!

fix_gmt_display() {
	 TZ_IN=$1
	 if echo $TZ_IN | grep -q '\\' ; then
	  [ "${TZ_IN:4:1}" = '-' ] && echo $TZ_IN | tr '-' '+'
	  [ "${TZ_IN:4:1}" = '+' ] && echo $TZ_IN | tr '+' '-'
	 else
	  [ "${TZ_IN:3:1}" = '-' ] && echo $TZ_IN | tr '-' '+'
	  [ "${TZ_IN:3:1}" = '+' ] && echo $TZ_IN | tr '+' '-'
	 fi
}
OUT=`fix_gmt_display $1`

[ -n "$OUT" ] && echo $OUT
