#!/bin/ash

if [ $# -lt 2 -o "$1" = "-h" -o "$1" = "--help" ]; then
	SHBASE="`basename $0`"
	echo "${SHBASE} v1"
	echo ""
	echo "Usage: $SHBASE [-h]"
	echo "       $SHBASE partition password"
	echo ""
	echo "Example:"
	echo "  $SHBASE sdc3 pass1234"
	echo ""
	echo "Warning1:"
	echo "  All current files on the specified partition will be lost."
	echo "Warning2:"
	echo "  If you forget the password,"
	echo "  all files on the LUKS partition will become inaccessible."
	exit 1
fi

exit_error() {
	echo "$@"
	exit 1
}

[ "$(which cryptsetup)" ] || exit_error "\"cryptsetup\" utility not found."

PART_NAME="$1"
MYPASSWORD="$2"

if [ ! "`busybox blkid /dev/$PART_NAME`" ] ; then
	exit_error "Partition \"$PART_NAME\" not found."
fi

echo "Formating \"$PART_NAME\" as Luks."
echo -n "$MYPASSWORD" | cryptsetup luksFormat "/dev/$PART_NAME" -
[ $? -eq 0 ] || exit_error "Luks format of \"$PART_NAME\" failed."
echo -n "$MYPASSWORD" | cryptsetup open "/dev/$PART_NAME" "lukspartition_${PART_NAME}" -
[ $? -eq 0 ] || exit_error "Luks open of \"/dev/$PART_NAME\" failed."
sync
echo "Formating \"lukspartition_${PART_NAME}\" as ext4."
mkfs.ext4 -q "/dev/mapper/lukspartition_${PART_NAME}"
sync
sleep 1
cryptsetup close "lukspartition_${PART_NAME}"

### END ###