#!/bin/sh

usage() {
	echo "
usage: ${0##*/} [options] set

set menu for many desktop environments and applications
using ${SYSROOT}/etc/xdg/menus/puppy.menu

options:
  -sysroot <path>: set system root
"
	exit
}

MENUS='
applications.menu
cinnamon-applications.menu
gnome-applications.menu
gnome-flashback-applications.menu
kde4-applications.menu
kf5-applications.menu
lxde-applications.menu
lxlauncher-applications.menu
lxqt-applications.menu
mate-applications.menu
moblin-applications.menu
xfce-applications.menu
'

#===========================================================

[ -z "$1" ] && usage

for i in $@ ; do
	case $1 in
		-prefix|-sysroot) SYSROOT="$2" ; shift 2 ;;
		set|-set) PSET=1 ;;
		*) usage ;;
	esac
done

[ "$PSET" != "1" ] && exit

if [ -f ${SYSROOT}/etc/xdg/menus/puppy.menu ] ; then
	cd ${SYSROOT}/etc/xdg/menus
	cp puppy.menu pup.menu
	for i in $MENUS ; do
		rm -f $i
		ln -sv pup.menu $i
	done
else
	echo "ERROR: ${SYSROOT}/etc/xdg/menus/puppy.menu not found..."
	exit 1
fi

### END ###