#!/bin/ash

OPT_QUIET=

for i in $@
do
	case $i in
		-a|--auto) todo=1 ;;
		-q|--quiet) OPT_QUIET=1 ;;
		-v|--verbose) todo=1 ;;
		-h|--help)
			echo '
ifplugstatus [options] [INTERFACE]
   -a --auto            Enable interface automatically (off)
   -q --quiet           Quiet behaviour (off)
   -h --help            Show this help
   -V --version         Show version number'
			exit
			;;
		-V|--version)
			echo 'ifplugstatus 0.28 (SVN: 124)'
			exit
			;;
		*-) echo -n ;;
		*) break ;;
	esac
	shift
done

#=====================================================

detect_link_beat() {
	[ "$1" ] || return 10
	if [ ! -e /sys/class/net/${1} ] ; then
		if [ ! "$OPT_QUIET" ] ; then
			echo "$1: not supported"
			echo "Failure (No such device)"
		fi
		return 11
	fi
	if [ -e /sys/class/net/${1}/carrier ] ; then
		read carrier < /sys/class/net/${1}/carrier
		if [ "$carrier" = "1" ] ; then
			if [ ! "$OPT_QUIET" ] ; then
				echo "${interface}: link beat detected"
			fi
			return 0
		fi
	fi
	#---
	if [ ! "$OPT_QUIET" ] ; then
		echo "${interface}: unplugged"
	fi
	return 1
}

#----

if [ -z "$1" ] ; then
	for i in /sys/class/net/*
	do
		[ -e $i ] || continue
		interface=${i##*/}
		detect_link_beat $interface
	done
	exit
fi

#----

interface=${1##*/}
if ! detect_link_beat $interface ; then
	exit 1
fi

### END ###