#!/bin/ash
#javaiftest - To be run from command line, to see results.
echo -e "\nEnvironment:"
echo -e "JAVA_HOME=$JAVA_HOME"
javaifchange
echo -e "\n.javaifrc:"
if [ -f /root/.javaifrc ]; then
 cat /root/.javaifrc
 echo
fi
echo -en "\nwhich java:   "
if which java 2>/dev/null; then
 echo -n "which javaws: "
 which javaws 2>/dev/null || echo ''
 echo -e "\njava -version:"
 java -version
 if which javaws &>/dev/null \
   && javaws --help | grep -q '-version'; then
  echo -e "\njavaws -version:"
  javaws -version
 fi
else
 echo "Java is not installed."
 exit
fi

echo -e "\nPATH=$PATH"
echo -e "\nLD_LIBRARY_PATH=$LD_LIBRARY_PATH"

if which javac >/dev/null; then #JDK installed
 echo '/**
 * The HelloWorldApp class implements an application that
 * simply prints "Hello World!" to standard output.
 */
class HelloWorldApp {
    public static void main(String[] args) {
        System.out.println("Hello World!"); // Display the string.
    }
}' > /tmp/HelloWorldApp.java
 cd /tmp
 echo -e "\njavac -verbose HelloWorldApp.java:"
 javac HelloWorldApp.java
else
 cd /usr/lib/javaif
fi

echo -e "\njava HelloWorldApp (expect Hello World!):"
java HelloWorldApp

if which javaws &>/dev/null; then
 echo -en "\nEnter any character to run an interactive JNLP example,\nand/or <Enter>: "
 read REPLY
 if [ -n "$REPLY" ]; then
  cd /usr/lib/javaif
  echo -e "\njavaws InputVerificationDemo.jnlp:"
  javaws InputVerificationDemo.jnlp 2>/dev/null
  if [ $? -eq 0 ]; then
   echo 'Demonstration Completed'
  else
   echo 'Demonstration Aborted'
  fi
 fi
fi
