#!/bin/bash
#120201 rodin.s: internationalized.
#130527 extract code that bumps user to root to script 'user2root'.
#130531 explain root, finn and spot.
#130601 offer run some internet apps as user 'spot'. see also usr/sbin/setup-spot and 3builddistro (in woof).
#130604 use actual names of executables, passed to setup-spot. multiple spot checkboxes.
#130723 pre-populate /root/.spot-status.

export TEXTDOMAIN=loginmanager
export TEXTDOMAINDIR=/usr/share/locale
export OUTPUT_CHARSET=UTF-8
. gettext.sh

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505

#========================================================================
set_password() {
	#change root password, and require password to 'su root'...
	USER=$1
	PASSWORD="$(/usr/lib/gtkdialog/box_passwd --confirm "Change password for: $USER" "Please enter a password for $USER, minimum six characters.")"
	if [ $? -eq 0 ] ; then
		echo "${USER}:${PASSWORD}" | busybox chpasswd -c sha512
		if [ $? -eq 0 ] ; then
			mkdir -p /var/local/chgdpasswd/
			echo -n > /var/local/chgdpasswd/${USER}
			/usr/lib/gtkdialog/box_ok "Login Manager" complete "Password successfully changed."
		fi
	fi
}

spot_dlg() {
	touch /root/.spot-status
	SPOTCHECKS=''
	if [ -s /root/.spot-status ];then
		#organise checkboxes into 3 rows per column...
		SPOTCHECKS='<vbox>'
		CNT=0
		for ASPOTLIST in `cat /root/.spot-status`
		do
			[ ! "$ASPOTLIST" ] && continue
			CNT=$(($CNT + 1))
			case $CNT in
				4) SPOTCHECKS="${SPOTCHECKS}</vbox><vbox>" ;;
				7) SPOTCHECKS="${SPOTCHECKS}</vbox><vbox>" ;;
				10) SPOTCHECKS="${SPOTCHECKS}</vbox><vbox>" ;;
			esac
			ANAME="`echo -n "$ASPOTLIST" | cut -f 1 -d '='`"
			AVALUE="`echo -n "$ASPOTLIST" | cut -f 2 -d '='`"
			SPOTCHECKS="${SPOTCHECKS}<checkbox><label>${ANAME}</label><variable>CHECK_${ANAME}</variable><default>${AVALUE}</default></checkbox>"
		done
		SPOTCHECKS="${SPOTCHECKS}</vbox>"
	fi

	export SPOT_DIALOG='
<window title="Login and Security Manager" icon-name="gtk-execute" resizable="false">
 <vbox space-expand="true" space-fill="true">
	<hbox>
		<pixmap><input file>/home/spot/spot.png</input></pixmap>
		<frame spot>
			<vbox>
				<text><label>'$(gettext "Logged in as administrator, it is possible to run some Internet applications as user 'spot'. This gives theoretical extra security.")'</label></text>
				<hbox>
					<vbox>
					<text width-chars="14"><label>'$(gettext 'Tick apps to run as spot:')'</label></text>
					</vbox>
					'${SPOTCHECKS}'
				</hbox>
			</vbox>
		</frame>
	</hbox>
  
	<hbox>
		<text space-expand="true" space-fill="false"><label>"       "</label></text>
		<button ok></button>
		<button cancel></button>
	</hbox>
 </vbox>
</window>
'
	#echo "$SPOT_DIALOG" > /tmp/loginmanager_SPOT.xml #debug
	RETSTRING="`gtkdialog --program=SPOT_DIALOG --center`"
	[ $? -ne 0 ] && exit
	eval "$RETSTRING"
	[ "$EXIT" != "OK" ] && return
	if [ -s /root/.spot-status ];then
		for ASPOTLIST in `echo "$RETSTRING" | grep '^CHECK_'`
		do
			ACHECKNAME="`echo -n "$ASPOTLIST" | cut -f 1 -d '='`"
			ANAME="`echo -n "$ACHECKNAME" | cut -f 2- -d '_'`"
			AVALUE="`echo -n "$ASPOTLIST" | cut -f 2 -d '"'`" #'geany
			ORIGVALUE="$(grep "^${ANAME}=" /root/.spot-status | cut -f 2 -d '=')"
			if [ "$AVALUE" != "$ORIGVALUE" ];then
				/usr/lib/gtkdialog/box_ok "$(gettext 'Security Manager:') ${ANAME}" nb "$(eval_gettext 'If ${ANAME} is running please exit it now, then click OK button...')"
				setup-spot "${ANAME}=${AVALUE}"
				case $AVALUE in
				true)
					M_sm1="$(eval_gettext "The next time that you start \${ANAME}, it will run as user 'spot'.")

$(gettext 'Note, this restricts where you can download and save files to, and where they can be edited. You are restricted to /home/spot, and the default folder is /home/spot/Downloads.')

$(eval_gettext 'Note also, if you move or copy any files into /home/spot while ${ANAME} is running, you may be able to open but not edit them, as they may not have permissions/ownership rights for spot -- exiting and restarting ${ANAME} will automatically fix this.')"
					;;
				false)
					M_sm1="$(eval_gettext "The next time that you start \${ANAME}, it will run as the 'root' user (administrator).")

$(gettext 'Note, this gives you complete freedom to download, save and edit files anywhere in the system.')"
					;;
				esac
				/usr/lib/gtkdialog/box_ok "$(gettext 'Security Manager:') ${ANAME}" complete "$M_sm1"
			fi
		done
	fi
}

export -f set_password
export -f spot_dlg

#========================================================================

#130723 pre-populate .spot-status... 130822 add firefox...
for ONEAPP in seamonkey QtWeb opera firefox palemoon midori slimjet light netsurf iron min chromium google-chrome
do
	[ "$(which ${ONEAPP})" = "" ] && continue
	[ "$(grep "${ONEAPP}" /root/.spot-status)" = "" ] && echo "${ONEAPP}=false" >> /root/.spot-status
done

#===================================================================

export MAIN_DIALOG='
<window title="Login and Security Manager" icon-name="gtk-execute" resizable="false">
 <vbox space-expand="true" space-fill="true">
	<hbox>
		<pixmap><input file>/usr/share/doc/puppylogo96.png</input></pixmap>
		<vbox>
			<vbox>
				<text>
					<label>'$(gettext "Puppy is structured in such a way that we consider running as administrator (also known as 'root') to be safe, and is the choice of most users.")'</label>
				</text>
			</vbox>
			<vbox>
				<button>
					<label>'$(gettext 'Set administrator password')'</label>
					<action>set_password root</action>
				</button>
			</vbox>
			<vbox>
				<button>
					<label>'$(gettext 'Configure applications to run as spot...')'</label>
					<action>spot_dlg</action>
				</button>
			</vbox>
		</vbox>
	</hbox>

	<hbox>
		<button space-expand="false" space-fill="false">
			'"`/usr/lib/gtkdialog/xml_button-icon help`"'
			<label>"'$(gettext 'Help')'"</label>
			<action>basichtmlviewer file:///usr/share/doc/root.htm & </action>
		</button>
		<text space-expand="true" space-fill="false"><label>"       "</label></text>
		<button space-expand="false" space-fill="false">
			'$(/usr/lib/gtkdialog/xml_button-icon quit.svg)'
			<label>Quit</label>
			<action type="exit">Cancel</action>
		</button>
	</hbox>
 </vbox>
</window>
'

#echo "$MAIN_DIALOG" > /tmp/loginmanager.xml #debug
gtkdialog --program=MAIN_DIALOG --center

###END###
