#!/bin/sh
#Barry Kauler, April 2011, GPL3 (/usr/share/doc/legal)
#intended to be called by rc.shutdown on 1st boot, create a non-root saved session.
#note, /usr/sbin/loginmanager is able to revert fido back to root.
#110918 run with or without X.
#111003 change from Xdialog to pupdialog.
#120317 L18L: set group/permissions for /dev/console
#120409 if using minit instead of busybox init.

. /etc/rc.d/PUPSTATE

if grep -q fido /etc/inittab && [ -d /home/fido ]; then
	msg="The system is already configured to run under a normal user (fido)"
	if [ $DISPLAY ];then
		/usr/lib/gtkdialog/box_ok "Message" info "$msg"
	else
		dialog --title 'Message' --msgbox "$msg" 10 40
	fi
	exit
fi

if [ ! -d /home/fido ] ; then
	CHANGE_ROOT_PASS=yes
	cp -P -a /root /home/fido
	# change /root to /home/$USER
	root_stuff=$(grep -r "/root" /home/$USER | sed 's|:.*||' | sort -u)
	[ "$root_stuff" != "" ] && sed -i "s%/root%/home/$USER%g" $root_stuff
fi

# -h means affect symlinks instead of target, -R means recursive...
busybox chown -h -R fido:users /home/fido
busybox chmod g+s /home/fido
busybox chown -h -R spot:spot /home/fido/spot

# fix broken symlinks..
ln -sf ../../usr /home/fido/.usr
ln -sf ../../etc /home/fido/.etc
ln -sf ../../usr/share/X11/rgb.txt /home/fido/.rgb.txt

# fix /etc/passwd
sed -i "s%/root/fido%/home/fido%" /etc/passwd
sed -i "s%/root/%/home/fido/%" /etc/passwd

#modify /etc/inittab to autologin as fido...
userEXPR='s%autologin root %autologin fido %'
sed -i -e "$userEXPR" /etc/inittab
#120409 if using minit instead of busybox init...
if [ -f /etc/minit/getty/1/params  ];then #see my minit pet pkg.
 EXPR2='s%^root$%fido%'
 sed -i -e "$EXPR2" /etc/minit/getty/1/params
fi

#stuff from pizzasgood, http://www.murga-linux.com/puppy/viewtopic.php?t=47410
#i don't know why setting these /dev permissions reverts to that in rootfs-skeleton
#on next boot, so have changed them in rootfs-skeleton also...
# ...oh, i think snapmergepuppy (when boot from usb) does not save /dev.
busybox chmod 770 /dev/zero
busybox chmod 770 /dev/ptmx
#set the setuid bit...
busybox chmod u+s `which ddcprobe`
[ "`which Xorg`" ] && busybox chmod u+s `which Xorg`

#120317 L18L: ref http://murga-linux.com/puppy/viewtopic.php?t=71358&start=60
chgrp users /dev/console
chmod g+w /dev/console

#busybox has to be configured with CONFIG_FEATURE_SUID_CONFIG (ex: busybox-1.17.2-1-w5.pet)
busybox chmod u+s `which busybox`
#see docs on busybox.conf at: http://www.softforge.de/bb/suid.html
#also: http://www.slitaz.org/en/doc/scratchbook/base-system.html
echo '[SUID]
reboot = ssx root.0   # reboot can be run by anyone and runs with euid=0/egid=0
poweroff = ssx root.0
halt = ssx root.0
su = ssx root.root
# passwd = ssx root.root
loadkmap = ssx root.root
mount = ssx root.root
umount = ssx root.root
ps = ssx root.0
kill = ssx root.0
' > /etc/busybox.conf

#i made /dev/pts 777 (was 707) in rootfs-skeleton in Woof.

[ "$CHANGE_ROOT_PASS" != "yes" ] && exit

#change root password, and require password to 'su root'...
ROOTPASSWORD=""
while [ "$ROOTPASSWORD" = "" ]
do
	if [ "$DISPLAY" ] ; then
		ROOTPASSWORD="$(/usr/lib/gtkdialog/box_passwd --show "Change admin passwd" "First shutdown: ask admin password." "Please enter a password for the administrator (root), minimum six characters. Login as fido does not require a password, so at bootup you will go directly to the desktop. This is also the case if you had chosen to run as administrator. However, having chosen the restricted fido user, you will be required to enter a password whenever you want to perform an operation that requires admin priviledges. PLEASE REMEMBER THIS PASSWORD")"
	else
		ROOTPASSWORD="`dialog --title "First shutdown: ask admin password" --stdout --nocancel --inputbox "Please enter a password for the administrator (root), minimum six characters.\n\nLogin as fido does not require a password, so at bootup you will go directly to the desktop. This is also the case if you had chosen to run as administrator. However, having chosen the restricted fido user, you will be required to enter a password whenever you want to perform an operation that requires admin priviledges.\n\nPLEASE REMEMBER THIS PASSWORD" 0 0 ""`"
	fi
done

echo "root:${ROOTPASSWORD}" | busybox chpasswd #--md5
#sudo asks for user password, not root, simple solution give same password to both...
#(that is the default, but i have specified runaspw in /etc/sudoers to ask for root pw)
echo "fido:${ROOTPASSWORD}" | busybox chpasswd #--md5

#note, /usr/sbin/loginmanager enables to change back to root afterward.

### END ###
