#!/bin/ash
# generic wrapper to run as ${XUSER} (when currently running as root)
# (C) James Budiono 2012, 2017
# License: GPL version 3 or later
#

#set -x

XUSER=spot

case $0 in *run-as|*run-as-user)
	if ! [ "$1" ] ; then
		echo "$0: Specify user"
		exit 1
	fi
	XUSER=$1
	shift
esac

CWD=$PWD
CMD=''
while [ "$1" ]; do
	CMD="$CMD \"$1\""
	shift
done

[ "$CMD" ] || exit

USER_HOME=$(awk -F: '$1=="'"${XUSER}"'" {print $6}' /etc/passwd)
if ! [ "$USER_HOME" ] ; then
	echo "$0 ERROR: could not HOME dir for user $XUSER"
	exit 1
fi
CURDIR=$PWD

if [ $(id -u) -eq 0 ]; then
	[ $XAUTHORITY ] && cp $XAUTHORITY ${USER_HOME}/.Xauthority 2>/dev/null
	touch ${USER_HOME}/.Xauthority
	export XAUTHORITY=$USER_HOME/.Xauthority

	export XDG_CONFIG_HOME=$USER_HOME/.config
	export XDG_CACHE_HOME=$USER_HOME/.cache
	export XDG_DATA_HOME=$USER_HOME/.local/share
	if [ "$XDG_RUNTIME_DIR" ] ; then
		export XDG_RUNTIME_DIR=/tmp/runtime-${XUSER}
		if [ ! -d $XDG_RUNTIME_DIR ] ; then
			mkdir -p $XDG_RUNTIME_DIR
			chmod 0700 $XDG_RUNTIME_DIR
			chown ${XUSER}:${XUSER} $XDG_RUNTIME_DIR
		fi
	fi
	export DBUS_SESSION_BUS_ADDRESS=""

	exec su ${XUSER} -s /bin/ash -c '
# try to switch to original directory, unless it is /root
! [ "'"$CURDIR"'" = /root ] && cd "'"$CURDIR"'"
exec '"$CMD"'
'
else
	exec ash -c "exec $CMD"
fi

### END ###
