#!/bin/sh
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#sends a request to /usr/sbin/savepuppyd to save the session.
#v4.01 19may2008 BK: request now to /sbin/pup_eventd (savepuppyd is history).
#v411 /tmp/snapmergepuppyrequest is processed in /sbin/pup_event_frontend_d. (from v403 i think)
#101221 fix yaf-splash.
#111012 remove LANG=C

. /etc/rc.d/PUPSTATE
if [ $PUPMODE -ne 3 -a $PUPMODE -ne 7 -a $PUPMODE -ne 13 ] ; then
  echo "save2flash: Wrong PUPMODE ($PUPMODE)"
  exit 1
fi

#export LANG=C
export DISPLAY=':0'

#LANG=C /usr/X11R7/bin/yaf-splash -display :0 -font "8x16" -outline 0 -margin 4 -bg yellow -text "NOTICE:
/usr/lib/gtkdialog/box_splash -bg yellow -close never -text "NOTICE:
Request to save current session is queued. Please wait, another message will popup when the saving occurs..." &
RETVAL=$?
YAFPID=$!

touch /tmp/snapmergepuppyrequest

while [ -f /tmp/snapmergepuppyrequest ];do
 sleep 1
done

[ $RETVAL -eq 0 ] && kill $YAFPID


###END###
