#!/bin/ash

[ -z "$WAYLAND_DISPLAY" ] || exit 0

. ~/.xkbrc

exec setxkbmap -model "$XKB_DEFAULT_MODEL" -layout "$XKB_DEFAULT_LAYOUT" -option "$XKB_DEFAULT_OPTIONS" -rules "$XKB_DEFAULT_RULES" -variant "$XKB_DEFAULT_VARIANT"