#!/bin/bash
#this script is started from $HOME/.jwmrc

export TEXTDOMAIN=jwm_config
export OUTPUT_CHARSET=UTF-8

echo '
<JWM>
	<Program label="'$(gettext 'Home')'" icon="/usr/local/lib/X11/pixmaps/home48.png">rox $HOME</Program>
	<Program label="'$(gettext 'System')'" icon="/usr/local/lib/X11/pixmaps/pc48.png">rox /</Program>
	<Program label="'$(gettext 'Network')'" icon="/usr/local/lib/X11/pixmaps/connect48.png">rox $HOME/network</Program>'
	[ -d $HOME/Downloads ] && echo '<Program label="'$(gettext 'Downloads')'" icon="/usr/local/lib/X11/pixmaps/folder48.png">rox $HOME/Downloads</Program>'
	echo '<Separator/>
	<Dynamic label="'$(gettext 'Drives')'" icon="/usr/local/lib/X11/pixmaps/drive48.png">exec:/usr/local/jwm_config/menu_build_places_drives</Dynamic>
	<Dynamic label="'$(gettext 'Recently used')'" icon="file.svg">exec:/usr/local/jwm_config/menu_build_recent_docs</Dynamic>
	<Separator/>
	<Program label="'$(gettext 'Web')'" icon="/usr/local/lib/X11/pixmaps/www48.png">defaultbrowser</Program>
	<Program label="'$(gettext 'Help')'" icon="/usr/local/lib/X11/pixmaps/help48.png">/usr/sbin/puppyhelp</Program>
</JWM>'
