#!/bin/bash
#this script is started from $HOME/.jwmrc

export TEXTDOMAIN=jwm
export OUTPUT_CHARSET=UTF-8

echo '
<JWM>
  <Program icon="preferences.svg" label="'$(gettext 'Activate mouse-action')'">exec /usr/local/jwm_config/shortcuts -mouse</Program>
</JWM>'
