#!/bin/ash

[ "$1" = 'stop' ] && exit 0

STATUS=1
if [ -d '/sys/firmware/efi/efivars' ]; then
	if [ "$(grep 'efivarfs' /proc/mounts)" ]; then
		STATUS=0
	else
		modprobe efivarfs
		if [ $? -eq 0 ]; then
			mount -t efivarfs none /sys/firmware/efi/efivars
			STATUS=$?
		fi
	fi
fi

exit $STATUS
