#!/bin/sh

if [ -f usr/share/applications/abiword.desktop ] ; then
	sed -i \
		-e 's%Name=.*%Name=AbiWord word processor%' \
		-e 's%Exec=.*%Exec=abiword%' \
		-e 's%Icon=.*%Icon=/usr/share/pixmaps/puppy/write.svg%' \
		-e 's%Categories=.*%Categories=WordProcessor%' \
			usr/share/applications/abiword.desktop
fi
