#!/bin/sh

rm -rf etc

#slackware
if [ -f bin/mktemp-gnu ] ; then
	mv bin/mktemp-gnu bin/mktemp
fi

[ "$DISTRO_BINARY_COMPAT" = "void" ] && mv -f usr/bin ./bin

#delete invalid symlinks
find -L . -type l -delete
