#!/bin/sh

mkdir -p etc/init.d
mkdir -p var/lib/dbus/ 

#slackware
case $DISTRO_BINARY_COMPAT in
	slackware*)
		mv etc/rc.d/* etc/init.d/
		find etc/init.d -type f -name '*.new' -delete # may or may not be there
		echo '# newer slackware dbus needs system user "polkitd"
if [ -f etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf ];then
	if grep -q "polkitd" etc/dbus-1/system.d/org.freedesktop.PolicyKit1.conf ;then
		chroot . addgroup -g 87 -S polkitd
		sleep 1
		chroot . adduser -S -D -H -h /var/lib/polkit -u 87 -s /bin/false -G polkitd polkitd
		echo "Adding policy kit user"
	fi
fi' > pinstall.sh
		;;
esac

#===================================================================
# for some reason dbus-uuidgen fails with --ensure 

if [ -f etc/init.d/rc.messagebus ] ; then
	# slackware
	#      echo "Starting system message bus:  /usr/bin/dbus-uuidgen --ensure ; /usr/bin/dbus-daemon --system"
	#      /usr/bin/dbus-uuidgen --ensure
	sed -i 's|    /usr/bin/dbus-uuidgen.*|    /usr/bin/dbus-uuidgen > /var/lib/dbus/machine-id ; ln -s /var/lib/dbus/machine-id /etc/machine-id 2>/dev/null|' \
		etc/init.d/rc.messagebus
elif [ -f etc/init.d/dbus ] ; then
	if grep -q '$UUIDGEN_OPTS' etc/init.d/dbus ; then
		#ubuntu trusty xenial bionic ~
		#  # Create machine-id file
		#  if [ -x $UUIDGEN ]; then
		#    $UUIDGEN $UUIDGEN_OPTS
		#  fi
		sed -i 's|$UUIDGEN_OPTS|> /var/lib/dbus/machine-id ; ln -s /var/lib/dbus/machine-id /etc/machine-id 2>/dev/null|' etc/init.d/dbus
	elif grep -q '--ensure=/etc/machine-id' ; then
		# alpine
		sed -i 's|--ensure=/etc/machine-id|> /var/lib/dbus/machine-id ; ln -s /var/lib/dbus/machine-id /etc/machine-id 2>/dev/null|' etc/init.d/dbus
	fi
fi
