#!/bin/sh

list='DejaVuSans-BoldOblique.ttf
DejaVuSans-Bold.ttf
DejaVuSansMono-Oblique.ttf
DejaVuSansMono.ttf
DejaVuSans-Oblique.ttf
DejaVuSans.ttf'

dj=$(find . -name DejaVuSans.ttf)
dir=$(dirname $dj)

mkdir -p TTF
for i in $list
do
	mv ${dir}/${i} TTF/
done

rm -rf usr etc

mkdir -p usr/share/fonts/default/
mv TTF usr/share/fonts/default/

