#!/bin/sh

find -name '*Italic.ttf' -delete

NLSDIR=`pwd`_NLS
mkdir -p $NLSDIR/usr/share/fonts/truetype/noto
mv -f usr/share/fonts/truetype/noto/*.ttf $NLSDIR/usr/share/fonts/truetype/noto/
mv -f $NLSDIR/usr/share/fonts/truetype/noto/{NotoSans,NotoSerif,NotoMono}-*.ttf $NLSDIR/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf usr/share/fonts/truetype/noto/
mv -f usr/share/fonts/opentype $NLSDIR/usr/share/fonts/

mkdir -p etc/fonts/conf.d
cat << EOF > etc/fonts/conf.d/01-noto.conf
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
    <its:translateRule translate="no" selector="/fontconfig/*[not(self::description)]"/>
  </its:rules>

  <description>Default to Noto</description>
	<match target="pattern">
		<test qual="any" name="family" compare="eq"><string>DejaVu Sans</string></test>
		<edit name="family" mode="assign" binding="same"><string>Noto Sans</string></edit>
	</match>
	<match target="pattern">
		<test qual="any" name="family" compare="eq"><string>DejaVu Serif</string></test>
		<edit name="family" mode="assign" binding="same"><string>Noto Serif</string></edit>
	</match>
	<match target="pattern">
		<test qual="any" name="family" compare="eq"><string>DejaVu Mono</string></test>
		<edit name="family" mode="assign" binding="same"><string>Noto Mono</string></edit>
	</match>
	<alias>
		<family>serif</family>
		<prefer>
			<family>Noto Serif</family>
		</prefer>
	</alias>
	<alias>
		<family>sans-serif</family>
		<prefer>
			<family>Noto Sans</family>
		</prefer>
	</alias>
	<alias>
		<family>monospace</family>
		<prefer>
			<family>Noto Mono</family>
		</prefer>
	</alias>
</fontconfig>
EOF

cat << EOF > pinstall.sh
[ -e usr/share/fonts/TTF/DejaVuSans.ttf ] && rm -f etc/fonts/conf.d/01-noto.conf
EOF