#!/bin/sh

if [ -f usr/share/applications/gadmin-rsync.desktop ] ; then
	sed -i \
		-e 's%Name=.*%Name=GAdmin-Rsync remote backup%' \
		-e 's%Exec=.*%Exec=gadmin-rsync%' \
		-e 's%Icon=.*%Icon=gadmin-rsync%' \
		-e 's%Categories=.*%Categories=Archiving%' \
			usr/share/applications/gadmin-rsync.desktop
fi
