#!/bin/sh

mkdir -p usr/share/applications

cat > usr/share/applications/galculator.desktop <<EOF
[Desktop Entry]
Name=Galculator scientific calculator
Comment=Perform simple and scientific calculations
Exec=galculator
Icon=galculator.xpm
Terminal=false
Type=Application
Categories=Calculator
StartupNotify=true
Encoding=UTF-8
GenericName=Galculator
EOF

### END ###