#!/bin/sh

if [ -f usr/share/applications/gftp.desktop ] ; then
	sed -i \
		-e 's%Name=.*%Name=gFTP ftp client%' \
		-e 's%Exec=.*%Exec=gftp%' \
		-e 's%Categories=.*%Categories=X-Internet%' \
			usr/share/applications/gftp.desktop
fi

if [ ! -e usr/bin/gftp -a -f usr/bin/gftp-gtk ] ; then
	ln -sv gftp-gtk usr/bin/gftp
fi

[ -f usr/share/gftp/gftprc ] && gftprc=usr/share/gftp/gftprc
[ -f etc/gftp/gftprc ] && gftprc=etc/gftp/gftprc

if [ ! -z $gftprc ] ; then
	echo 'ext=.pet:tar.xpm:B:
ext=.sfs:tar.xpm:B:' >> $gftprc
fi
