#!/bin/sh

if [ -f usr/share/applications/gnumeric.desktop ] ; then
	sed -i \
		-e 's%Name=.*%Name=Gnumeric spreadsheet editor%' \
		-e 's%Exec=.*%Exec=gnumeric%' \
		-e 's%Icon=.*%Icon=/usr/share/icons/hicolor/48x48/apps/gnumeric.png%' \
		-e 's%Categories=.*%Categories=X-Calculate%' \
			usr/share/applications/gnumeric.desktop
fi
