#!/bin/sh

rm -rf usr/share/icons

cat > usr/share/applications/leafpad.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Leafpad text editor
Icon=leafpad.png
Comment=Leafpad text editor
Exec=leafpad
Terminal=false
Type=Application
Categories=TextEditor
GenericName=Leafpad text editor
EOF

