#!/bin/sh

if [ -f usr/share/applications/mhwaveedit.desktop ] ; then
	sed -i \
		-e 's%Name=.*%Name=mhWaveEdit audio recorder/editor%' \
		-e 's%Icon=.*%Icon=/usr/share/pixmaps/puppy/edit_sound.svg%' \
		-e 's%Categories=.*%Categories=AudioVideo%' \
			usr/share/applications/mhwaveedit.desktop
fi
