#!/bin/bash

find usr/share/applications -iname '*firefox*' -exec sed -i 's, %.$,,g' '{}' \;

# use firefox dir first if found, if not found use firefox*
FF=`find usr/ -type d -name 'firefox' -maxdepth 2`
[ "$FF" == "" ] && FF=`find usr/ -type d -name 'firefox*' -maxdepth 2`

mkdir -p ${FF}/browser/defaults/preferences
PREFDIR="${FF}/browser/defaults/preferences"

cat > ${PREFDIR}/local-settings.js <<_EOF
//
//default home page
pref("browser.startup.homepage", "data:text/plain,browser.startup.homepage=file:///usr/share/doc/home.htm");
_EOF

(cd usr/${PLIB}/firefox*
[ -f omni.ja ] && mkdir omnidir
mv omni.ja omnidir/omni.zip
cd omnidir
unzip omni.zip
rm omni.zip
zip -0 -y -R ../newomni '*'
cd ..
mv newomni.zip omni.ja
rm -r omnidir)

(
echo "echo '"'#!/bin/sh'"' > usr/local/bin/defaultbrowser"
echo "echo 'exec firefox \"\$@\"' >> usr/local/bin/defaultbrowser"
echo "chmod 755 usr/local/bin/defaultbrowser"
echo "echo '"'#!/bin/sh'"' > usr/local/bin/defaulthtmlviewer"
echo "echo 'exec firefox \"\$@\"' >> usr/local/bin/defaulthtmlviewer"
echo "chmod 755 usr/local/bin/defaulthtmlviewer"
echo 'echo "setting up Firefox"'
) > pinstall.sh

### END ###
