#!/bin/sh

if [ -f usr/share/applications/mpv.desktop ] ; then
	sed -i \
		-e 's%Name=.*%Name=mpv Media Player%' \
		-e 's%Exec=.*%Exec=mpv --player-operation-mode=pseudo-gui%' \
		-e 's%Icon=.*%Icon=mpv.png%' \
		-e 's%Categories=.*%Categories=X-Multimedia-mediaplayer%' \
			usr/share/applications/mpv.desktop
fi
