#!/bin/sh

SYSLINUXBINS='chain.c32
ldlinux.c32
libcom32.c32
libutil.c32
vesamenu.c32
isolinux.bin
ldlinux.sys
mbr.bin
mbrfat.bin
memdisk
syslinux.com
syslinux.exe"
'

if ! [ -d usr/share/syslinux ] ; then
	exit
fi

(
cd usr/share/syslinux
ls * | while read i ; do
	case $SYSLINUXBINS in
		*"$i"*) continue  ;;
		*) rm -f $i ;;
	esac
done
)
