#!/bin/sh

# debian: /etc/init.d/hwclock.sh conflicts with rc.country
rm -rf etc
rm -rf ${PLIB}/udev ${PLIB}/systemd

#delete invalid symlinks
find -L . -type l -delete

# ubuntu
[ -f usr/bin/rename.ul ] && mv usr/bin/rename.ul usr/bin/rename

mkdir -p var/lock
