#!/bin/sh

for i in $PLIBDIRS # $PLIBDIRS is exported in 2createpackages
do
	[ -d $i ] || continue
	[ -e ${i}/libchromeXvMCPro.so.1 ] && ln -snf libchromeXvMCPro.so.1 ${i}/libchromeXvMCPro.so
	[ -e ${i}/libchromeXvMC.so.1 ] && ln -snf libchromeXvMC.so.1 ${i}/libchromeXvMC.so
	[ -e ${i}/libI810XvMC.so.1 ] && ln -snf libI810XvMC.so.1 ${i}/libI810XvMC.so
	[ -e ${i}/libIntelXvMC.so.1 ] && ln -snf libIntelXvMC.so.1 ${i}/libIntelXvMC.so
	#also has dri modules, but this is a cutdown pkg...
	rm -rf ${i}/xorg/modules/dri 2> /dev/null
done

# slackware, these X servers get through...
rm -f usr/bin/Xfbdev 2> /dev/null
rm -f usr/bin/Xsdl   2> /dev/null
rm -f usr/bin/Xdmx   2> /dev/null
rm -f usr/bin/Xfbdev 2> /dev/null
rm -f usr/bin/*dmx*  2> /dev/null

# usr/bin/X must be a symlink to Xorg
ln -snf Xorg usr/bin/X
