#!/bin/bash

[ -f $HOME/.jwm/menuheights ] && . $HOME/.jwm/menuheights
[ ! $MENHEIGHT ] && MENHEIGHT=24

echo '<?xml version="1.0"?>
<JWM>'
jwm-xdgmenu /etc/xdg/menus/puppy-desktop.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-system.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-setup.menu $MENHEIGHT
echo '<Separator/>'
jwm-xdgmenu /etc/xdg/menus/puppy-utility.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-filesystem.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-graphic.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-document.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-calculate.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-personal.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-network.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-internet.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-multimedia.menu $MENHEIGHT
jwm-xdgmenu /etc/xdg/menus/puppy-fun.menu $MENHEIGHT
echo '<Separator/>
<Program label="'$(gettext 'Help')'" icon="help48.png">exec defaulthtmlviewer file:///usr/share/doc/index.html</Program>
<Program label="'$(gettext 'Leave')'" icon="shutdown48.png">/usr/sbin/logout_gui</Program>
</JWM>'

