#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t rootfs -o remount,rw rootfs /

ln -s /proc/mounts /etc/fstab 2>/dev/null

mount -t devtmpfs devtmpfs /dev 2>/dev/null

# busybox 1.25 losetup somehow requires /dev/loop/X in the initrd to work..
# edit: only if CONFIG_FEATURE_DEVFS is enabled
mkdir -p /dev/loop
ls /dev/loop[0-9]* | sed 's|/dev/loop||' | \
while read i ; do ln -sf ../loop${i} /dev/loop/${i} ; done

### END ###
