#!/bin/bash
export inputbox="
<window title=\"pFind\" icon-name=\"gtk-find\">
 <vbox>
  <frame $FRAME>
   <pixmap icon_size=\"6\"><input file stock=\"gtk-$IMG\"></input></pixmap>
   <text use-markup=\"true\"><label>\"$TXT1\"</label></text>
   <entry activates-default=\"true\">
    <variable>INPUT</variable>
    <input>echo \"$DEFAULT\"</input>
   </entry>
  </frame>
  <hbox>
   <button cancel>
    <input file icon=\"gtk-cancel\"></input>
    <action type=\"exit\">cancel</action>
   </button>
   <button can-default=\"true\" has-default=\"true\">
    <label>Ok</label>
    <input file icon=\"gtk-ok\"></input>
    <action type=\"exit\">ok</action>
   </button>
  </hbox>
 </vbox>
</window>"
echo "$inputbox" > /root/test

I=$IFS; IFS=""
for STATEMENTS in  $(gtkdialog -p inputbox --class=jwm-ontop --center); do
	eval $STATEMENTS
done
IFS=$I
TXT1=""; DEFAULT=""; FRAME=""; IMG="" #reset to avoid alien text in next box
