#!/bin/bash
export TEXTDOMAIN=pfind

if [ -z "$FRAME" ]; then FRAME="$(gettext 'Info')"; fi
export yesno_box='
<window title="pFind" icon-name="gtk-find">
 <vbox>
  <frame '$FRAME'>
   <pixmap icon_size="6"><input file stock="gtk-'$IMG'"></input></pixmap>
   <vbox scrollable="true" height="100" width="300" width-request="10" height-request="10">
    <text width-request="1000" use-markup="true"><label>"'$TXT1'"</label></text>
   </vbox>
   <text><label>"'$TXT2'"</label></text>
  </frame>
  <hbox>
   <button>'"
    <input file icon=\"gtk-no\"></input>
    <label>$(gettext \"No\")</label>
    <action type=\"exit\">no</action>
   </button>
   <button can-default=\"true\" has-default=\"true\" use-stock=\"true\">
    <input file icon=\"gtk-yes\"></input>
    <label>$(gettext \"Yes\")</label>
    <action type=\"exit\">yes</action>
   </button>
  </hbox>
 </vbox>
</window>"
I=$IFS; IFS=""
for STATEMENTS in  $(gtkdialog -p yesno_box --center); do
	eval $STATEMENTS
done
IFS=$I
TXT1=""; TXT2=""; IMG=""; FRAME="" #reset to avoid alien values in next box