# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind.enablesound", false);
user_pref("browser.cache.disk.capacity", 10240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 61440);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.chrome.toolbar_style", 0);
user_pref("browser.display.use_document_fonts", 0);
user_pref("browser.download.dir", "/root/Downloads");
user_pref("browser.enable_automatic_image_resizing", true);
user_pref("browser.open.dir", "/usr/share/doc");
user_pref("browser.open.filterIndex", 0);
user_pref("browser.rights.1.shown", true);
user_pref("browser.search.defaultengine", "engine:///usr/lib/seamonkey/searchplugins/google.src");
user_pref("browser.search.opensidebarsearchpanel", false);
user_pref("browser.startup.homepage", "file:///usr/share/doc/home.htm");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.4");
user_pref("browser.tabs.autoHide", false);
user_pref("browser.tabs.loadInBackground", true);
user_pref("browser.tabs.opentabfor.middleclick", true);
user_pref("browser.tabs.opentabfor.urlbar", true);
user_pref("browser.toolbars.showbutton.print", false);
user_pref("dom.disable_open_during_load", true);
user_pref("editor.prettyprint", false);
user_pref("font.default.x-western", "sans-serif");
user_pref("font.minimum-size.x-western", 12);
user_pref("font.name.cursive.x-western", "serif");
user_pref("font.name.fantasy.x-western", "serif");
user_pref("font.name.monospace.x-western", "monospace");
user_pref("font.name.sans-serif.x-western", "DejaVu Sans");
user_pref("font.name.serif.x-western", "serif");
user_pref("font.size.fixed.x-western", 14);
user_pref("font.size.variable.x-western", 14);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("ldap_2.servers.default.filename", "default.mab");
user_pref("ldap_2.servers.default.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.default.uri", "moz-abldapdirectory://default.mab");
user_pref("ldap_2.servers.history.filename", "history.mab");
user_pref("ldap_2.servers.history.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.pab.filename", "abook.mab");
user_pref("ldap_2.servers.pab.replication.lastChangeNumber", 0);
user_pref("mail.biff.play_sound", false);
user_pref("mail.forward_message_mode", 2);
user_pref("mail.spellcheck.inline", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.share_proxy_settings", true);
user_pref("prefs.converted-to-utf8", true);
user_pref("privacy.popups.first_popup", false);
user_pref("privacy.popups.remove_blacklist", false);
user_pref("security.OCSP.URL", "");
user_pref("security.OCSP.signingCA", "");
user_pref("security.disable_button.changePassword", false);
user_pref("security.disable_button.resetPassword", false);
user_pref("security.enable_java", false);
user_pref("security.password_lifetime", 0);
user_pref("update_notifications.enabled", false);
user_pref("update_notifications.provider.0.last_checked", 1139662619);
/*
user_pref("network.protocol-handler.app.mailto", "mailto.sh");
user_pref("network.protocol-handler.external.mailto", true);
user_pref("network.protocol-handler.warn-external.mailto", false);
*/
