#!/bin/ash
# called from ptheme_gtk
# link special theme icons to */.DirIcon for ROX-Filer

ICON_THEME="${ICON_THEME:-Puppy Standard}"
[ -n "$1" ] && ICON_THEME="$1"
echo "$ICON_THEME"
ORDER='scalable|48'
[ "$ICON_THEME" = 'Tango' ] && ORDER='48|scalable' # Tango is a cut down theme
THEME_PLACES="$(find "/usr/share/icons/$ICON_THEME" -type d -name 'places' | grep -E "$ORDER" |tail -n1)" # use biggest we can find
[ -z "$THEME_PLACES" ] && THEME_PLACES="$(find "/usr/share/icons/$ICON_THEME" -type d -name '48*' | grep 'places')" # fallback, some themes have different heirarchy

# link
ln_diricon() {
	EPATH=$1
	ICON=$2
	[ -e "$ICON" ] && \
		(cd "$EPATH"; ln -svf "$ICON" ./.DirIcon )
}

# check if from theme
check_diricon () {
	DELPATH=$1
	THEME_PATH="$2"
	[ -h "$DELPATH/.DirIcon" ] && readlink "$DELPATH/.DirIcon" | grep -q "$THEME_PATH" ||\
	rm -f "$DELPATH/.DirIcon"
}

for icon in $(ls "$THEME_PLACES/" | grep "^folder");do
	
	if echo $icon|grep -q 'home' ;then
			check_diricon "$HOME/$dir" "$THEME_PLACES"
			ln_diricon "$HOME" "$THEME_PLACES/$icon"
			continue # home
	else
		for dir in Documents Downloads my-documents my-applications network Music Video Images ; do
			[ "$dir" = 'network' ] && i=remote || i=$dir
			[ -e "$HOME/$dir" ] && ICON=`echo $icon|grep -i "${i#*-}"`
			echo "$ICON" | grep -q 'symbolic' && continue
			check_diricon "$HOME/$dir" "$THEME_PLACES"
			[ -n "$ICON" ] && ln_diricon "$HOME/$dir"  "$THEME_PLACES/$ICON"
		done
	fi
done
