#!/bin/sh

rm -rf etc

#slackware
if [ -f bin/mktemp-gnu ] ; then
	mv bin/mktemp-gnu bin/mktemp
fi

[ "$DISTRO_BINARY_COMPAT" = "void" ] && mv -f usr/bin ./bin

#260323 for ubuntu with Rust coreutils-from-uutils
echo "Rust coreutils move binaries"
[ -d usr/lib/cargo/bin/coreutils ] && mv -vf usr/lib/cargo/bin/coreutils/* usr/bin

#delete invalid symlinks
find -L . -type l -delete
