#!/bin/sh
#if the pkg created in packages-woof has something wrong, this file is a last
#resort to fix it. Current-dir is where this file FIXUPHACK is located.

# Xorg/X is in xserver-xorg..
rm -f usr/bin/X

#slackware: /etc/X11/xkb
#debian   : /usr/share/X11/xkb

#slackware: usr/share/X11/xkb/ is already a symlink..
#           created by the slackware post-install script (most likely)
if [ ! -L usr/share/X11/xkb ] ; then
	#debian
	mv -f usr/share/X11/xkb/* etc/X11/xkb/ 2>/dev/null
	rm -rf usr/share/X11/xkb/
	ln -sv ../../../etc/X11/xkb usr/share/X11/xkb
fi

# http://packages.slackware.com/?r=slackware-14.2&p=libX11-1.6.4-i586-1_slack14.2.txz&f
# http://packages.ubuntu.com/xenial/libx11-data -> http://packages.ubuntu.com/xenial/all/libx11-data/filelist
# slackware: libX11
# debian:    libX11-data
# keep: C en_US.UTF-8 iso8859-1 iso8859-2 iso8859-15 [following old template]
# pkg template should not have 'nls>null'. Have to copy stuff from NLS dir.
#   ,nls     is the preferred option
#   ,nls>exe is acceptable
if [ -d ../xorg_base_new_NLS ] ; then
	mkdir -p usr/share/X11/locale/
	cp -af ../xorg_base_new_NLS/usr/share/X11/locale/* usr/share/X11/locale/
else
	if [ ! -d usr/share/X11/locale/C ] ; then
		echo '!!! ERROR: ../xorg_base_new_NLS MISSING !!!'
	fi
fi
find usr/share/X11/locale  -mindepth 1 -maxdepth 1 -type d | \
	grep -Ev '/C$|/en_US.UTF-8$|/iso8859-1$|/iso8859-2$|/iso8859-15$' | \
		while read dir ; do
			rm -rf "$dir"
		done

#100416 ubuntu lucid has moved libGL.so* to /usr/lib/mesa (why oh why!!!???)...
#note, but not libGLU.so*
if [ -e usr/lib/mesa/libGL.so.1 ];then
 ln -s mesa/libGL.so.1 usr/lib/libGL.so.1
 ln -s mesa/libGL.so usr/lib/libGL.so
 ln -s mesa/libGL.so.1.2 usr/lib/libGL.so.1.2
fi

#120406 gxmessage pkg creates xmessage symlink to it (in pinstall.sh). get real xmessage out of the way...
if [ -f usr/bin/xmessage ];then
 if [ ! -h usr/bin/xmessage  ];then
  mkdir -p usr/local/bin
  mv -f usr/bin/xmessage usr/local/bin/
 fi
fi

#===================================

#if /etc/fonts/fonts.conf is not present, use traditional Puppy-style font settings
if [ -f etc/fonts/fonts.conf ];then
	rm -rf etc/fonts-puppy
else
	rm -rf etc/fonts
	mv etc/fonts-puppy etc/fonts
fi

ln -sv ../../../etc/X11/app-defaults usr/share/X11/app-defaults
rm -rf etc/X11/xinit

mkdir -p var/cache/fontconfig

# Bitmaps that are shared between X applications are in an odd place..
if [ -d ../xorg_base_new_DEV/usr/include/X11/bitmaps ] ; then
	mkdir -p usr/include/X11/
	mv -f ../xorg_base_new_DEV/usr/include/X11/bitmaps usr/include/X11/
fi

#====================================================

mkdir -p usr/share/applications
mkdir -p usr/share/pixmaps

cat > usr/share/applications/Xcalc-scientific-calculator.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Xcalc scientific calculator
Icon=/usr/share/pixmaps/puppy/calculator.svg
Comment=Xcalc scientific calculator
Exec=xcalc
Terminal=false
Type=Application
Categories=Calculator
GenericName=Xcalc scientific calculator
EOF

cat > usr/share/applications/Xclipboard.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Xclipboard
Icon=/usr/share/pixmaps/puppy/paste.svg
Comment=Xclipboard
Exec=xclipboard 
Terminal=false
Type=Application
Categories=X-DesktopApplets
GenericName=Xclipboard
NoDisplay=true
EOF

cat > usr/share/applications/xconsole.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Xconsole monitor console
Icon=/usr/share/pixmaps/puppy/terminal.svg
Comment=Xconsole monitor console /dev/console
Exec=xconsole -verbose
Terminal=false
Type=Application
Categories=TerminalEmulator
GenericName=Xconsole
NoDisplay=true
EOF

cat > usr/share/applications/Xfontsel-font-viewer.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Xfontsel font viewer
Icon=/usr/share/pixmaps/puppy/font.svg
Comment=Xfontsel font viewer
Exec=xfontsel -bg "#e0ffe0"
Terminal=false
Type=Application
Categories=X-DesktopApplets
GenericName=Xfontsel font viewer
NoDisplay=true
EOF

cat > usr/share/applications/xkill.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Xkill - kill a window
Icon=xkill.svg
Comment=Xkill - kill a window
Exec=xkill
Terminal=false
Type=Application
Categories=Utility
GenericName=kill x-windows
EOF

cat > usr/share/applications/Xorg-Video-Wizard.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Screen/Graphics Wizard
Icon=/usr/share/pixmaps/puppy/graphics.svg
Comment=Xorg Video Wizard
Exec=xorgwizard
Terminal=false
Type=Application
Categories=X-SetupWizard
GenericName=Screen/Graphics Wizard
EOF

#====================================================

cat > usr/share/pixmaps/xkill.svg <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" height="100" width="100">
  <g style="fill:#000;stroke:#fff;stroke-width:3;">
    <path d="M 40,60 Q 34,60 34,55 Q 34,47 23,47 Q 17,47 16,39 Q 14,29 16,17 C 17,13 18,5 41,3 Q 50,2 59,3  C 82,5 83,13 84,17 Q 86,29 84,39 Q 83,47 77,47 Q 66,47 66,55 Q 66,59 60,59 L 60,56 40,56 z M 77,89 17,67 Q 14,66 11,67 C 0,71 0,62 7,58 C 2,47 14,44 18,58 Q 18,61 22,63 L 79,83 Q 83,85 85,82 C 92,74 100,81 92,89 C 98,96 85,100 81,92 Q 80,90 77,89 z "/>
    <path d="M 23,89 83,67 Q 86,66 89,67 C 100,71 100,62 93,58 C 98,47 86,44 82,58 Q 82,61 78,63 L 21,83 Q 17,85 15,82 C 8,74 0,81 8,89 C 2,96 15,100 19,92 Q 20,90 23,89 z"/>
  </g>
  <path style="fill:#fff;stroke:#fff;stroke-width:3;" d="M 47,44 Q 43,46 43,49 Q 43,51 47,51 Q 48,50 47,44 z M 53,43 Q 57,46 57,49 Q 57,51 53,51 Q 52,50 53,43 z M 43,32 Q 38,28 31,27 C 20,26 21,36 25,38 Q 34,42 41,37 C 46,33 44,34 43,32 z M 57,32 Q 62,28 69,27 C 80,26 79,36 75,38 Q 66,42 59,37 C 54,33 56,34 57,32 z"/>
</svg>
EOF

#=====================================================

mkdir -p usr/lib/

if [ ! -f usr/lib/SecurityPolicy ] ; then
	cat > usr/lib/SecurityPolicy <<EOF
version-1 

# $Xorg: SecurityPolicy,v 1.3 2000/08/17 19:47:56 cpqbld Exp $

# The site policy fields are interpreted by the XC-QUERY-SECURITY-1
# authorization protocol.  The values are arbitrary and site-specific.
# Refer to the Security Extension Specification for the usage of the policies.
#sitepolicy A
#sitepolicy B
#sitepolicy C

# Property access rules:
# property <property> <window> <permissions>
# <window> ::= any | root | <propertyselector>
# <propertyselector> ::= <property> | <property>=<value>
# <permissions> :== [ <operation> | <action> | <space> ]*
# <operation> :== r | w | d
#	r	read
#	w	write
#	d	delete
# <action> :== a | i | e
#	a	allow
#	i	ignore
#	e	error

# Allow reading of application resources, but not writing.
property RESOURCE_MANAGER	root	ar iw
property SCREEN_RESOURCES	root	ar iw

# Ignore attempts to use cut buffers.  Giving errors causes apps to crash,
# and allowing access may give away too much information.
property CUT_BUFFER0	root	irw
property CUT_BUFFER1	root	irw
property CUT_BUFFER2	root	irw
property CUT_BUFFER3	root	irw
property CUT_BUFFER4	root	irw
property CUT_BUFFER5	root	irw
property CUT_BUFFER6	root	irw
property CUT_BUFFER7	root	irw

# If you are using Motif, you probably want these.
property _MOTIF_DEFAULT_BINDINGS	root	ar iw
property _MOTIF_DRAG_WINDOW	root	ar iw
property _MOTIF_DRAG_TARGETS	any 	ar iw
property _MOTIF_DRAG_ATOMS	any 	ar iw
property _MOTIF_DRAG_ATOM_PAIRS	any 	ar iw

# If you are running CDE you also need these
property _MOTIF_WM_INFO		root	arw
property TT_SESSION		root	irw
property WM_ICON_SIZE		root	irw
property "SDT Pixel Set"	any	irw

# The next two rules let xwininfo -tree work when untrusted.
property WM_NAME	any	ar

# Allow read of WM_CLASS, but only for windows with WM_NAME.
# This might be more restrictive than necessary, but demonstrates
# the <required property> facility, and is also an attempt to
# say "top level windows only."
property WM_CLASS	WM_NAME	ar

# These next three let xlsclients work untrusted.  Think carefully
# before including these; giving away the client machine name and command
# may be exposing too much.
property WM_STATE	WM_NAME	ar
property WM_CLIENT_MACHINE	WM_NAME	ar
property WM_COMMAND	WM_NAME	ar

# To let untrusted clients use the standard colormaps created by
# xstdcmap, include these lines.
property RGB_DEFAULT_MAP	root	ar
property RGB_BEST_MAP	root	ar
property RGB_RED_MAP	root	ar
property RGB_GREEN_MAP	root	ar
property RGB_BLUE_MAP	root	ar
property RGB_GRAY_MAP	root	ar

# To let untrusted clients use the color management database created
# by xcmsdb, include these lines.
property XDCCC_LINEAR_RGB_CORRECTION	root	ar
property XDCCC_LINEAR_RGB_MATRICES	root	ar
property XDCCC_GRAY_SCREENWHITEPOINT	root	ar
property XDCCC_GRAY_CORRECTION	root	ar

# To let untrusted clients use the overlay visuals that many vendors
# support, include this line.
property SERVER_OVERLAY_VISUALS	root	ar
EOF
fi

### END ###