#!/bin/sh
#150410 1.3.4 stop wpa_supplicant and dhcpcd directly vs. using frisbee.sh.
if grep -q '^frisbee_mode=1' /etc/frisbee/frisbee.conf;then
#	/etc/init.d/frisbee.sh stop #141018
	wpa_cli terminate 2>/dev/null #150410
	dhcpcd -k #150410
	sed -i -e '/^frisbee_mode=/ s/=.*/=0/' /etc/frisbee/frisbee.conf
	if grep -q '^dhcpcd_state_notify=1' /etc/frisbee/frisbee.conf;then
		[ -f /etc/dhcpcd_state_notify ] || touch /etc/dhcpcd_state_notify
	else
		rm -f /etc/dhcpcd_state_notify
	fi
	[ -d /tmp/.network_tray ] \
	 && rm -f /tmp/.network_tray/use_wireless_control_menu_labels \
	 || rm -f /tmp/.network_tray-use_wireless_control_menu_labels #140209
fi
