#!/bin/sh
#041222
. ./DISTRO_SPECS

DISTRO_TARGETARCH=i686

echo "Extracting the Void xml database from the archive"
mv -f Packages-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}pre ${DISTRO_TARGETARCH}-repodata.tar.zst
rm *.plist
tar --zstd -xf ${DISTRO_TARGETARCH}-repodata.tar.zst
rm ${DISTRO_TARGETARCH}-repodata.tar.zst
echo
echo "Converting the Void xml database to the Puppy PPM format (@JamesBond)"
rm Packages-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}
support/void/cvt.sh > Packages-${DISTRO_BINARY_COMPAT}-${DISTRO_COMPAT_VERSION}
