#!/bin/sh

# wl_colpick

# requires grim, slurp, netpbm, grep, sed
# GPLv2

export CGUI='<window title="Color Picker" resizable="false">
	<vbox>
		<hbox space-expand="true" space-fill="true">
			<text>
				<label>Click the place on screen where you want to fetch the color</label>
			</text>
			<button image-position="2">
				<input file icon="select-color"></input>
				<action>exit:SCREEN</action>
			</button>
		</hbox>
		<hseparator></hseparator>
			<text use-markup="true">
				<label>"<big>OR</big>"</label>
			</text>
		<hseparator></hseparator>
		<hbox space-expand="true" space-fill="true">
			<text>
				<label>Choose a color from the color button palette</label>
			</text>
			<colorbutton>
				<default>#FF00FF</default>
				<variable>CHOSEN</variable>
			</colorbutton>
		</hbox>
		<hseparator></hseparator>
		<hbox>
			<button ok></button>
		</hbox>
	</vbox>
</window>'

eval $(gtkdialog -p CGUI)
echo $EXIT
case $EXIT in
	# needs sleep, dunno why
	SCREEN)C=$(pos="$(slurp -b FFFFFF00 -p)";sleep 3; grim -g "$pos" -t ppm - | ppmtoxpm | grep -m1 '\" c.*\"' | sed -e 's/\" c //' -e 's/\".*$//')
	;;
	OK)C=$CHOSEN;;
	*)exit;;
esac

echo 'window {
 background-color:'$C';
}' > /tmp/wl_colpick.css


echo $C
echo '<window title="Color Picker" resizable="false">
	<vbox>
		<hbox>
			<text use-markup="true"><label>"<span background='"'#BBBBBB'"'>Select and copy/paste the color string below</span>"</label></text>
		</hbox>	
		<hbox space-expand="true" space-fill="true">	
			<text selectable="true" use-markup="true"><label>"<big>'$C'</big>"</label></text>
		</hbox>
		<hbox>	
			<button ok></button>
		</hbox>
	</vbox>
</window>' | gtkdialog -s --styles=/tmp/wl_colpick.css >/dev/null 2>&1
