#!/bin/bash
$APPDIR/func -reset_gtk
export TEXTDOMAIN=pmusic
export OUTPUT_CHARSET=UTF-8
[ "$1" != "-txt1_file" ] && echo "$TXT1" > $WORKDIR/box_ok_txt1
[ -z "$IMG" ] && IMG="dialog-error"
[ -z "$FRAME" ] && FRAME="$(gettext 'Error')"
if [ "$IMG" = "info" ]; then #offer link to wiki in the heading for info boxes
	WIKI_TXT='
	<text width-request="20" '$SF'><label>""</label></text>
	<text wrap="false" ypad="50" use-markup="true" '$SF'>
	 <label>"<u><span color='"'blue'"'>'$(gettext 'Online Help')'</span></u>"</label>
	</text>'
	WIKI_LINK='<action signal="button-press-event">export GTK2_RC_FILES='$HOME'/.gtkrc-2.0; '$BROWSER' http://wikka.puppylinux.com/pmusicDoc &</action>'
	IMG=dialog-information
fi 

[ "$HEADING" ] && $APPDIR/func_svg -heading "$HEADING"
S='
<window icon-name="pmusic" title="pMusic" allow-grow="true" default-width="500">
 <vbox>'
  [ "$HEADING" ] && S=$S'
  <vbox '$SF'>
   <hbox spacing="0" height="75" scrollable="false" '$ST' vscrollbar-policy="3" hscrollbar-policy="3">
    <eventbox name="svgheading" hover-selection="true" '$ST'>
     <hbox '$ST'>
     '$WIKI_TXT'
      <text '$ST'><label>""</label></text>
       <vbox '$SF'>
        <pixmap ypad="5" icon_size="6"><input file icon="'$IMG'"></input></pixmap>
      </vbox>
      <text '$SF'><label>""</label></text>
     </hbox>
     '$WIKI_LINK'
    </eventbox>
   </hbox>
  </vbox>'
  S=$S'<vbox scrollable="true" shadow-type="0" height="200" '$ST'>
   <frame '$FRAME'>'
    [ ! "$HEADING" ] && S=$S'<pixmap icon_size="6"><input file icon="'$IMG'"></input></pixmap>'
    S=$S'<text use-markup="true" selectable="true" can-focus="false" '$ST'><input file>'$WORKDIR'/box_ok_txt1</input></text>'
    [ "$TXT2" ] && S=$S'<text use-markup="true" selectable="true" can-focus="false"><label>"'$TXT2'"</label></text>'
   S=$S'</frame>
  </vbox>
  <hbox '$SF'>
   <button can-default="true" has-default="true" use-stock="true">
    <input file icon="ok"></input>
    <label>'$(gettext 'Ok')'</label>
   </button>
  </hbox>
 </vbox>
</window>'

export ok_box="$S"
XDG_DATA_DIRS=$WORKDIR:$XDG_DATA_DIRS $GTKDIALOG -p ok_box --center --styles=$APPDIR/themes/$THEME/gtk-3.0/gtk.css
TXT1=""; TXT2=""; IMG=""; FRAME="" #reset to avoid alien values in next box
