#!/bin/bash
#pMusic
#GPL - Copyright Sigmund Berglund

awk -F '|' '{print "|" $2 "|" $3 "|" $4 "|" $5}' $WORKDIR/playlist > $WORKDIR/playlist1
[ ! -d "$STORAGE_DIR/storage_playlist/" ] && mkdir "$STORAGE_DIR/storage_playlist/"
DATO="`date +%Y\_%m\_%d\_\(%H:%M:%S\)`"

#check if list is not empty
if [ -s $WORKDIR/playlist ]; then
	while read I; do
		[ ! "`diff "$STORAGE_DIR/storage_playlist/$I" $WORKDIR/playlist1`" ] && exit
	done <<< "`ls -1 "$STORAGE_DIR/storage_playlist/"`"
	cp $WORKDIR/playlist1 "$STORAGE_DIR/storage_playlist/Playlist_$DATO"
	echo "Playlist_""$DATO" > $WORKDIR/PLAYLIST_NAME
	#keep only the 30 newest in storage
	ls -1 "$STORAGE_DIR/storage_playlist/" | tail -n 30 > $WORKDIR/tmp_ls
	ls -1 "$STORAGE_DIR/storage_playlist/" > $WORKDIR/tmp_ls2
	while read I; do
		[[ "$(<$WORKDIR/tmp_ls)" != *"$I"* ]] && rm "$STORAGE_DIR/storage_playlist/$I"
	done < $WORKDIR/tmp_ls2
fi
exit 0
