#!/bin/bash
#pMusic - build gtkdialog xml code
#GPL - Copyright Sigmund Berglund

export TEXTDOMAIN=pmusic
export OUTPUT_CHARSET=UTF-8

GUI_VOLUME='
<hscale draw-value="false" scale-step="1" scale-min="0" scale-max="95" tooltip-text="'$(gettext 'Volume')'
'$(gettext 'Speaker channel')': '$SPEAKER'">
 <variable>VOLUME</variable>
 <input file>'$WORKDIR'/VOLUME</input>
 <action>. '$APPDIR'/func_mixer -set_volume</action>
 <action>refresh:MUTE</action>
</hscale>'

GUI_VOLUME_V='
<vscale name="mixer_vol_sliderV" width-request="22" draw-value="false" scale-step="1" scale-min="0" scale-max="95" inverted="true" tooltip-text="'$(gettext 'Volume')'
'$(gettext 'Speaker channel')': '$SPEAKER'" '$ST'>
 <variable>VOLUME</variable>
 <input file>'$WORKDIR'/VOLUME</input>
 <action>. '$APPDIR'/func_mixer -set_volume</action>
 <action>refresh:MUTE</action>
</vscale>'

GUI_VOLUME_IMG='
<pixmap>
 <height>12</height>
 <input file>'$APPDIR'/themes/'$THEME'/volume.svg</input>
</pixmap>
'

GUI_BALANCE='
<hscale draw-value="false" scale-step="1" scale-min="0" scale-max="200" tooltip-text="'$(gettext 'Balance')'
'$(gettext 'Speaker channel')': '$SPEAKER'" '$SF'>
 <variable>BALANCE</variable>
 <input file>'$WORKDIR'/BALANCE</input>
 <action>. '$APPDIR'/func_mixer -set_volume</action>
 <action signal="button-release-event">'$APPDIR'/func_mixer -check_stereo</action>
 <action>refresh:MUTE</action>
</hscale>
'

GUI_BUTTON_MIXER='
<button tooltip-text="'$(gettext 'Sound processing')'" '$SF'>
 <input file stock="gtk-volume"></input>
 <action>'$APPDIR'/func_mixer -gui &</action>
</button>'

GUI_BUTTON_MUTE='
<button relief="2" file-monitor="true" tooltip-text="'$(gettext 'Mute audio')'" '$SF'>
 <variable>MUTE</variable>
 <input file>'$WORKDIR'/icon_mute.svg</input>
 <height>22</height>
 <action>. '$APPDIR'/func_mixer -mute</action>
 <action>refresh:MUTE</action>
</button>'

GUI_MIXER='
<vbox spacing="0">
 <text height-request="2" '$SF'><label>""</label></text>
 <hbox spacing="0" homogeneous="true" '$ST'>
  <vbox>
   <text use-markup="true" wrap="false" angle="90" '$SF'><label>"<b><i><span size='"'large'"' fgcolor='"'#555555'"'>'$(gettext 'Volume')'</span></i></b>  "</label></text>
   <text '$ST'><label>""</label></text>
   <text use-markup="true" wrap="false" '$SF'><label>"<b><span color='"'#FF6D00'"'>'$(gettext 'L')'</span></b>"</label></text>
  </vbox>
  <vbox '$ST'>
   '$GUI_VOLUME_V'
  </vbox>
  <vbox '$SF'>
   '$GUI_BUTTON_MUTE'
   <text '$ST'><label>""</label></text>
   <text use-markup="true" wrap="false" '$SF'><label>"<b><span color='"'#FF6D00'"'>'$(gettext 'R')'</span></b>"</label></text>
  </vbox>
 </hbox>
 '$GUI_BALANCE'
</vbox>'


#input sound processing - controlled by ffmpeg
if [ -s $WORKDIR/ffmpeg_filter ]; then
	FF_VOLUME="`awk -F 'volume=' '{print $2}' $WORKDIR/ffmpeg_filter | cut -d',' -f1`"
	FADE_IN="`awk -F 'afade=t=in:d=' '{print $2}' $WORKDIR/ffmpeg_filter | cut -d',' -f1`"
	TREBLE="`awk -F 'treble=gain=' '{print $2}' $WORKDIR/ffmpeg_filter | cut -d',' -f1`"
	BASS="`awk -F 'bass=gain=' '{print $2}' $WORKDIR/ffmpeg_filter | cut -d',' -f1`"
	TEMPO="`awk -F 'atempo=' '{print $2}' $WORKDIR/ffmpeg_filter | cut -d',' -f1 | tr -d '.'`"
	PITCH="`awk -F 'pitch=' '{print $2}' $WORKDIR/ffmpeg_filter | cut -d',' -f1`"
fi
[ ! "$FF_VOLUME" ] && FF_VOLUME=1.0
[ ! "$FADE_IN" ] && FADE_IN=0
[ ! "$TREBLE" ] && TREBLE=0
[ ! "$BASS" ] && BASS=0
[ ! "$PITCH" ] && PITCH=1.0
[ ! "$TEMPO" ] && TEMPO=100
#read status for normalize checkbox
NORMALIZE="`grep -F NORMALIZE $CONFIG 2> /dev/null | cut -d= -f2`"


GUI_NORMALIZE='
<checkbox tooltip-text="'"$(gettext "Unify volume of all tracks.

This is handy when your tracks comes from different sources, since the recording level is not the same.")"'" '$SF'>
 <label>'$(gettext 'Normalize')'</label>
 <variable>NORMALIZE</variable>
 <default>'$NORMALIZE'</default>
 <action>. '$APPDIR'/func_config -write_config</action>
</checkbox>'

GUI_SOUND_INPUT='
<vbox '$ST'>
 <hbox '$SF'>
  '$GUI_NORMALIZE'
  <text width-request="20" '$ST'><label>""</label></text>
  <text><label>"'$(gettext 'Fade in (sec)')'"</label></text>
  <spinbutton width-request="40" editable="false" range-max="9" range-min="0" '$SF'>
    <variable>FADE_IN</variable>
    <default>'$FADE_IN'</default>
    <action>'$APPDIR'/func_mixer -activate_effects</action>
   </spinbutton>
  </hbox>
 <hseparator></hseparator>
 <hbox height-request="120" '$ST'> 
  <hbox '$SF'>
   <text xalign="1" yalign="1" use-markup="true" wrap="false" angle="90" '$SF'><label>"<b>'$(gettext 'Treble')'</b>"</label></text>
   <vscale width-request="39" range-max="10" range-min="-20" range-step="1" value-pos="2" inverted="true" '$SF'>
    <variable>TREBLE</variable>
    <default>'$TREBLE'</default>
    <item>"0|2|dB"</item>
    <action>'$APPDIR'/func_mixer -activate_effects</action>
   </vscale>
   <vscale width-request="28" range-max="10" range-min="-20" range-step="1" value-pos="2" inverted="true" '$SF'>
    <variable>BASS</variable>
    <default>'$BASS'</default>
    <item>"0|0|"</item>
    <action>'$APPDIR'/func_mixer -activate_effects</action>
   </vscale>
   <text xalign="0" yalign="1" use-markup="true" wrap="false" angle="90" '$SF'><label>"<b>'$(gettext 'Bass')'</b>"</label></text>
  </hbox>

  <text width-request="30" '$ST'><label>""</label></text>

  <hbox spacing="0" '$SF'>
   <vscale width-request="28" range-max="1.3" range-min="0.7" range-step="0.05" value-pos="2" inverted="true" '$SF'>
    <variable>PITCH</variable>
    <default>'$PITCH'</default>
    <item>"1.0|2|"</item>
    <action signal="button-release-event">'$APPDIR'/func_mixer -activate_effects</action>
   </vscale>
   <text xalign="0" yalign="1" use-markup="true" wrap="false" angle="90" '$SF'><label>"<b>'$(gettext 'Pitch')'</b>"</label></text>
   <text width-request="20" space-expand="false" space-fill="false"><label>""</label></text>
   <vscale width-request="39" range-max="200" range-min="50" range-step="1" value-pos="2" inverted="true" '$SF'>
    <variable>TEMPO</variable>
    <default>'$TEMPO'</default>
    <item>"100|2|"</item>
    <action>'$APPDIR'/func_mixer -activate_effects</action>
   </vscale>
   <text xalign="0" yalign="1" use-markup="true" wrap="false" angle="90" '$SF'><label>"<b>'$(gettext 'Tempo')'</b> (%)"</label></text>
   <text width-request="20" space-expand="false" space-fill="false"><label>""</label></text>
   <vscale width-request="39" range-max="2.0" range-min="0.0" range-step="0.1" value-pos="2" inverted="true" '$SF'>
    <variable>FF_VOLUME</variable>
    <default>'$FF_VOLUME'</default>
    <item>"1.0|2|"</item>
    <action>'$APPDIR'/func_mixer -activate_effects</action>
   </vscale>
   <text xalign="0" yalign="1" use-markup="true" wrap="false" angle="90" '$SF'><label>"<b>'$(gettext 'Volume')'</b>"</label></text>
  </hbox>
 </hbox>
</vbox>'
