name: dpupbw32

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      release:
        type: boolean
        description: 'Upload release'
        required: true
        default: true

jobs:
  x86:
    uses: puppylinux-woof-CE/woof-CE/.github/workflows/build.yml@testing
    with:
      repo: puppylinux-woof-CE/woof-CE
      ref: testing
      name: 'BookwormPup32'
      version: '23.12'
      arch: x86
      compat-distro: debian
      compat-distro-version: dpupbw32
      kernel: 'debian-bookworm'
      prefix: dpupbw32
      artifact: BookwormPup32-${{ github.run_number }}
      retention: 1

  upload32:
    needs: x86
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: version
        run: echo "builddate=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: BookwormPup32-${{ github.run_number }}
          path: .
      - name: Generate SHA512 checksums
        run: |
          mv dpupbw32-23.12.iso BookwormPup32-23.12-${{ steps.version.outputs.builddate }}.iso
          find . -type f -name '*.sfs' -exec sha512sum {} \; > SHA512checksums.txt
          find . -type f -name '*.iso' -exec sha512sum {} \; >> SHA512checksums.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: BookwormPup32-23.12
          tag_name: BookwormPup32/release-${{ steps.version.outputs.builddate }}
          fail_on_unmatched_files: true
          files: |
            *.iso
            *.sfs
            SHA512checksums.txt
