#!/bin/sh

if [ "$1" == "" ]; then
LOG1=${WORKDIR}/tail
else
LOG1="$1"
fi

#GTKDIALOG="gtkdialog"
#TAIL_BUTTON="test"
#TAIL_BUTTON_ICON="cancel"

export pburn_tail="
<window title=\"$TAIL_TITLE\" icon-name=\"media-optical\">
<vbox>
 
         <terminal argv0=\"/bin/sh\"
	  			  scrollback-lines=\"100000\"
  	    	  	  has-focus=\"true\"
  			      text-background-color=\"#FFA500\"
			      text-foreground-color=\"#000000\">
	      <variable>vte0</variable>
	      <width>75</width>
	      <height>20</height>
          <input>echo \"HISTFILE=; tail -f $LOG1\"</input>
          <action signal=\"child-exited\">exit:EXIT</action>
        </terminal>
 
 <hbox homogeneous=\"true\">
  <button stock-icon-size=\"3\" height-request=\"50\" width-request=\"200\">
   <label>$TAIL_BUTTON</label>
   <input file stock=\"gtk-${TAIL_BUTTON_ICON}\"></input>
   <action>EXIT:tail_button</action>
  </button>
 </hbox>
</vbox>
</window>"

I=$IFS; IFS=""
for STATEMENTS in $($GTKDIALOG -p pburn_tail --center); do
	eval $STATEMENTS
done

OLDPIDS=`ps | grep 'tail -f $LOG1'  | grep -v 'grep tail -f $LOG1' | tr -s ' ' | sed -e 's%^ %%' | cut -f 1 -d ' ' | tr '\n' ' '`
kill $OLDPIDS 2>/dev/null

IFS=$I
