#!/bin/sh
for ONEDOTINSTALL in `ls -a | grep '\.INSTALL'`
do
 #reset functions
 function pre_install () { /bin/true; }
 function post_install () { /bin/true; }
 function pre_upgrade () { /bin/true; }
 function post_upgrade () { /bin/true; }
 function pre_remove () { /bin/true; }
 function post_remove () { /bin/true; }
 
 PKGVER="`echo $ONEDOTINSTALL | sed 's/[^-]*-//'`" #get version
 . ./$ONEDOTINSTALL #load functions
 pre_install $PKGVER
 post_install $PKGVER
done
