#!/bin/ash
#this generates xml code for a gtkdialog gui.
#it is NOT a standalone window
#
#the reason for using this template is to control global size
#
#usage :
# xml_scalegrip
#
#Sigmund Berglund, Mar 2014
#GPL

#read config if exist
if [ -s $HOME/.config/ptheme/gtkdialog_active ] ; then
	. $HOME/.config/ptheme/gtkdialog_active
fi
[ ! "$XML_SCALEGRIP_SIZE" ]	&& XML_SCALEGRIP_SIZE=20

#generate XML code
echo "<statusbar  name=\"ScaleGrip\" width-request=\"$XML_SCALEGRIP_SIZE\"></statusbar>"

# NOTE !
# to avoid frame around <statusbar>, Gtk-theming is used in ./xml_info
