#!/bin/sh
#100228 BK support default network tool.
#100325 BK support Simple Network Setup.
#16aug10 shinobar: netchoice. BK: but only if defaultconnect still set to 'exec connectwizard'.
#110505 support sudo for non-root user.
#130104 rerwin: add frisbee
#130117 rerwin: remove redundant CURREXEC test, per shinobar
#160120 rerwin: add use of new pgprs and frisbee interfaces; correct frisbee check; ignore frisbee if not active.

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505

CURREXEC="`cat /usr/local/bin/defaultconnect | tail -n 1 | tr -s " " | cut -f 2 -d " "`"
[ "$CURREXEC" = "gkdial" ] && CURREXEC="pupdial" #for older pups.

if [ "$CURREXEC" = "connectwizard" ];then #BK
  NETCHOICE=""
  #try determine which tool was used to setup networking...
  if [ -x /usr/local/frisbee/frisbee-main ] \
    && frisbee --test_active; then #130104 160120
   NETCHOICE='frisbee' #130104 160120
  elif [ -s /etc/simple_network_setup/connections ];then #100306 160120
   NETCHOICE='sns'
  else
    CHECKNEWWIZ="`ls -1 /etc/network-wizard/network/interfaces 2>/dev/null`"
    [ "$CHECKNEWWIZ" != "" ] && NETCHOICE='net-setup.sh'
  fi
  [ "$NETCHOICE" != "" ] && CURREXEC="$NETCHOICE"
fi
#16aug10 shinobar: end

RUNMODE="$1"

case $RUNMODE in
  --wizard) exec /usr/sbin/connectwizard 1>&2 ;;
  --connect)
   case $CURREXEC in #connect using default tool.
    net-setup.sh) exec /etc/rc.d/rc.network connect 1>&2 ;; #Dougal.
    pgprs|pgprs-connect) #160120...
     if [ -x /usr/sbin/pgprs ];then
      pgprs --connect >/dev/null
     else
      pppd call gprs-disconnect-chatmm
      killall pppd
      pgprs-connect
     fi ;; #guessing, i need help here.
    pupdial) pupdial ;;
    pppoe_gui) pppoe_gui ;;
    connectwizard) connectwizard ;;
    sns) /usr/local/simple_network_setup/rc.network ;;
    frisbee) #160120...
     if [ -x /usr/local/frisbee/connect ];then
      /usr/local/frisbee/connect
     else
      frisbee --connect
     fi
     ;; #130104
   esac
   ;;
  --disconnect) #disconnect using default tool.
   case $CURREXEC in
    net-setup.sh) exec /etc/rc.d/rc.network stop 1>&2 ;; #Dougal.
    pgprs|pgprs-connect) #160120...
     if [ -x /usr/sbin/pgprs ];then
      pgprs --disconnect >/dev/null
     else
      pppd call gprs-disconnect-chatmm
      killall pppd
     fi
     ;; #guessing, i need help here.
    pupdial) killall wvdial; killall pppd ;;
    pppoe_gui) pppoe_gui ;;
    connectwizard) connectwizard ;;
    sns) /usr/local/simple_network_setup/rc.network stop ;;
    frisbee) #160120...
     if [ -x /usr/local/frisbee/disconnect ];then
      /usr/local/frisbee/disconnect
     else
      frisbee --disconnect
     fi
     ;; #130104
   esac
   ;;
  *) exec /usr/local/bin/defaultconnect 1>&2  ;;
esac

###END###
