#!/bin/sh
#(c) Copyright 2013 Barry Kauler bkhome.org
#2013 Licence GPL3 (/usr/share/doc/legal).
#this is startup code, called from /sbin/pup_event_frontend_d
# (which in turn is called from /root/.xinitrd when X starts).

#exec &>/tmp/${0##*/}.log ; set -x #debug

sleep 3 #1 #let the dust settle after X has started. 120718 reduce 2 to 1. 121105 try 2, see also /usr/sbin/delayedrun. 121212
#w471 slow cpus need more delay (well, rox does)...
DELAYFACTOR=0
CPUMHZ=`grep -m 1 -i '^cpu MHz' /proc/cpuinfo | tr -d ' ' | cut -f 2 -d ':' | cut -f 1 -d '.'` #my laptop: 933.000
if [ $CPUMHZ ];then
 [ $CPUMHZ -gt 100 ] && DELAYFACTOR=$((1600 / $CPUMHZ)) #120829 L18L: need 1 sec for my 1514 MHZ CPU.  #`expr 1100 \/ $CPUMHZ`
else #120718 raspi: 697.95  my laptop: 4789.47
 BOGOMIPS=`grep -m 1 -i '^bogomips' /proc/cpuinfo | tr -d ' ' | cut -f 2 -d ':' | cut -f 1 -d '.'`
 [ $BOGOMIPS ] && [ $BOGOMIPS -gt 200 ] && DELAYFACTOR=`expr 2100 \/ $BOGOMIPS`
fi
[ $DELAYFACTOR -gt 0 ] && sleep $DELAYFACTOR

pidof X &>/dev/null || pidof Xorg &>/dev/null || exit #X not running.

echo -n "" > /tmp/pup_event_frontend_d_curpos.log #see frontend_timeout

. /etc/rc.d/PUPSTATE
PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/X11R7/bin"
. /etc/eventmanager #has RAMSAVEINTERVAL, HOTPLUGON, HOTPLUGNOISY, BACKENDON, POWERTIMEOUT
. /usr/local/pup_event/frontend_funcs

SCRNXY="`xwininfo -root | grep -o '\-geometry .*' | tr -s ' ' | cut -f 2 -d ' ' | cut -f 1 -d '+'`"
SCRN_X="`echo -n "$SCRNXY" | cut -f 1 -d 'x'`"
SCRN_Y="`echo -n "$SCRNXY" | cut -f 2 -d 'x'`"
echo -n "$SCRN_X" > /tmp/pup_event_frontend_scrn_x #read by frontend_change.
echo -n "$SCRN_Y" > /tmp/pup_event_frontend_scrn_y #read by frontend_change.

######################################################################
#stuff to setup at entry...
mkdir -p /root/.pup_event

#build the desktop icons...
DRV_CATEGORY='drive'
PROBEDISK="`probedisk`"

if [ "$HOTPLUGON" = "false" ];then
	#only show a single 'drives' icon on desktop...
	create_icon_func #needs DRV_NAME, DRV_CATEGORY, DRV_DESCRIPTION.
else
	PROBEPART="`probepart -k -extra-info | grep -E 'audiocd|btrfs|ext2|ext3|ext4|f2fs|hfs|iso9660|jfs|minix|msdos|ntfs|reiser|udf|vfat|exfat|xfs|crypto_LUKS'`"
	if [ "$FD0ICON" = "true" -a -e /sys/block/fd0 ];then #see /etc/eventmanager
		PROBEDISK="/dev/fd0|floppy|Legacy floppy drive
$PROBEDISK"
		PROBEPART="/dev/fd0|vfat|1440
$PROBEPART"
	fi
	while IFS="|" read ONEDRV DRV_CATEGORY DRV_DESCRIPTION zzz
	do
		DRV_NAME=${ONEDRV##*/}
		echo "$PROBEPART" | grep -q "$DRV_NAME" || continue #precaution (such as CD not inserted).
		create_icon_func startup #needs DRV_NAME, DRV_CATEGORY, DRV_DESCRIPTION, PROBEPART.
	done <<EOF
$PROBEDISK
EOF
fi

if [ "$BACKENDON" = "false" ];then #see /etc/eventmanager.
	killall frontend_timeout 2>/dev/null
	killall udevd 2>/dev/null
	exit 2
else
	PS="`busybox ps`" 
	echo "$PS" | grep -q udevd || {
		# this code also rc.sysinit
		. /etc/rc.d/BOOTCONSTRAINED
		if [ "$BOOT_UDEVDCHILDREN" ];then
			UDEV_LOG=2 udevd --daemon --resolve-names=early --children-max=${BOOT_UDEVDCHILDREN} & #BOOT_UDEVDCHILDREN=1 good idea?
		else
			UDEV_LOG=2 udevd --daemon --resolve-names=early &
		fi
		sleep 0.1
	}
fi

rm -f /tmp/pup_event_frontend_display

echo "DISPLAY='${DISPLAY}'" > /tmp/pup_event_frontend_display
echo "LANG='${LANG}'" >> /tmp/pup_event_frontend_display
echo "HOME='${HOME}'" >> /tmp/pup_event_frontend_display
echo "PATH='${PATH}'" >> /tmp/pup_event_frontend_display

PS="`busybox ps`"
echo "$PS" | grep -q /usr/local/pup_event/frontend_timeout || \
	/usr/local/pup_event/frontend_timeout &

killall -9 frontend_startup

### END ###