#!/bin/bash
#perform background housekeeping.

#exec &>/tmp/${0##*/}.log ; set -x #debug

if ! /usr/local/pup_event/frontend_startup $@ ; then
	exit 1
fi

MINUTE=0;

rm -f /tmp/services/pup_event_timeout

. /etc/eventmanager

# bash builtins: avoid calling some external apps.. specially sleep
for builtin in sleep basename dirname finfo head ln logname mkdir print printenv realpath rmdir sync uname
do
	if [ -f /usr/lib/bash/${builtin} ] ; then
		enable -f /usr/lib/bash/${builtin} ${builtin}
	fi
done

#===============================================

while [ 1 ]
do

	sleep 10

	if [ -f /tmp/frontend_change_processing_* ] ; then
		continue
	fi
	if [ -f /tmp/frontend_startup_lock ] ; then
		continue
	fi

	MINUTE=$(( $MINUTE + 10 ));
	if [ $MINUTE -eq 60 ] ; then
		MINUTE=0;
		/usr/local/pup_event/pup_event_timeout60
		. /etc/eventmanager
	fi

	[ "$HOTPLUGON" = "false" ] && continue #see /etc/eventmanager
	[ "$ICONDESK" = "false" ] && continue #see /etc/eventmanager
	[ ! -e /sys/block/sr0 ] && continue

	#unfortunately, we have to poll at regular intervals to see if a cd is inserted...
	for i in /sys/block/sr*
	do
		DRV_NAME=${i##*/}
		DRV_CATEGORY="optical"
		while read dev etc ; do #only check cd if unmounted.
			[ "$dev" = "/dev/${DRV_NAME}" ] && continue 2
		done < /proc/mounts
		#--
		cddetect_quick -d/dev/${DRV_NAME} >/dev/null 2>&1 #very fast.
		if [ $? -eq 0 ];then #inserted
			if [ ! -e /tmp/pup_event_frontend/drive_${DRV_NAME} ] ; then
				echo "add" > /sys/block/${DRV_NAME}/uevent
			fi
		else # not inserted
			if [ -e /tmp/pup_event_frontend/drive_${DRV_NAME} ] ; then
				echo "remove" > /sys/block/${DRV_NAME}/uevent
			fi
		fi
	done

done

### END ###
