name: Cleanup releases

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - build: Puppy-Kernel-6.18-x86_64-usrmerge/release-
          - build: Puppy-Kernel-6.18-x86_64/release-
          - build: Puppy-Kernel-6.18-x86-usrmerge/release-
          - build: Puppy-Kernel-6.18-x86/release-
    steps:
      - name: Delete old ${{ matrix.build }} releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          delete_tag_pattern: ${{ matrix.build }}
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
