name: debian-sid64

on:
  schedule:
    - cron: '0 0 2,16 * *'

jobs:
  build:
    if: github.repository == 'puppylinux-woof-CE/woof-CE'
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: sid64
      kernel: debian-sid
      artifact: ${{ github.workflow }}-${{ github.run_number }}
      retention: 15
