name: kernel-kit-k6.18

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'schedule' || (github.repository == 'puppylinux-woof-CE/woof-CE' && github.ref == 'refs/heads/testing')
    runs-on: ubuntu-24.04
    container:
      image: ${{ matrix.image }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - kernel-kit-config: 6.18.x-x86
            image: debian:trixie-slim
          - kernel-kit-config: 6.18.x-x86_64
            image: debian:trixie-slim
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends curl wget ca-certificates git file squashfs-tools xz-utils diffutils patch make flex bison python3 bc bzip2 kmod rsync libelf-dev libssl-dev dwarves gcc gcc-multilib jq
          curl https://raw.githubusercontent.com/puppylinux-woof-CE/initrd_progs/master/pkg/w_apps_static/w_apps/vercmp.c | gcc -x c -o /usr/local/bin/vercmp -
          echo "dash dash/sh boolean false" | debconf-set-selections
          DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
      - name: Build kernel
        run: |
          cd kernel-kit
          cp -f ${{ matrix.kernel-kit-config }}-build.conf build.conf
          CREATE_KBUILD_SFS=yes ./build.sh
          mkdir small-output
          mv `ls output/kernel_sources-*.sfs* output/kbuild-*.sfs* output/*.tar* 2>/dev/null` small-output
      - name: Upload kernel
        uses: actions/upload-artifact@v7
        with:
          name: kernel-kit-output-${{ matrix.kernel-kit-config }}
          path: kernel-kit/small-output
          retention-days: 16
  usrmerge:
    if: github.event_name != 'schedule' || (github.repository == 'puppylinux-woof-CE/woof-CE' && github.ref == 'refs/heads/testing')
    needs: build
    runs-on: ubuntu-24.04
    container:
      image: debian:trixie-slim
    continue-on-error: true
    strategy:
      matrix:
        kernel-kit-config: [6.18.x-x86, 6.18.x-x86_64]
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends squashfs-tools bzip2
      - name: Get build output
        uses: actions/download-artifact@v8
        with:
          name: kernel-kit-output-${{ matrix.kernel-kit-config }}
          path: kernel-kit/output
      - name: Repackage kernel
        run: |
          cd kernel-kit
          ./usrmerge.sh
      - name: Upload kernel
        uses: actions/upload-artifact@v7
        with:
          name: kernel-kit-output-usrmerge-${{ matrix.kernel-kit-config }}
          path: kernel-kit/output
          retention-days: 16
  release:
    runs-on: ubuntu-latest
    needs: usrmerge
    strategy:
      matrix:
        include:
          - kversion: 6.18
            arch: x86_64
            dirs: 
          - kversion: 6.18
            arch: x86_64
            dirs: -usrmerge
          - kversion: 6.18
            arch: x86
            dirs: 
          - kversion: 6.18
            arch: x86
            dirs: -usrmerge
    steps:
      - name: Get current date
        id: version
        run: echo "builddate=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: kernel-kit-output${{ matrix.dirs }}-${{ matrix.kversion }}.x-${{ matrix.arch }}
          path: .
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          name: Puppy-Kernels-${{ matrix.kversion }}-${{ matrix.arch }}${{ matrix.dirs }}
          tag_name: Puppy-Kernel-${{ matrix.kversion }}-${{ matrix.arch }}${{ matrix.dirs }}/release-${{ steps.version.outputs.builddate }}
          fail_on_unmatched_files: true
          files: |
            *.tar.bz2
            *.txt
            kbuild*
            kernel_sources*
