name: kernel-release

on:
  workflow_dispatch:
jobs:
  get-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - kversion: 6.1
          - kversion: 6.6
          - kversion: 6.12
          - kversion: 6.18
    steps:
      - name: Get current date
        id: version
        run: echo "builddate=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
      - name: Download artifact1
        uses: actions/download-artifact@v7
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: kernel-kit-output-${{ matrix.kversion }}.x-x86_64
          path: .
      - name: rename artifacts1
        run: for i in huge-* ; do mv $i ${{ matrix.kversion }}-x86_64-$i ; done
      - name: Download artifact2
        uses: actions/download-artifact@v7
        with:
          name: kernel-kit-output-usrmerge-${{ matrix.kversion }}.x-x86_64
          path: .
      - name: rename artifacts2
        run: for i in huge-* ; do mv $i ${{ matrix.kversion }}-x86_64-$i ; done
      - name: Download artifact3
        uses: actions/download-artifact@v7
        with:
          name: kernel-kit-output-${{ matrix.kversion }}.x-x86
          path: .
      - name: rename artifacts3
        run: for i in huge-* ; do mv $i ${{ matrix.kversion }}-x86-$i ; done
      - name: Download artifact4
        uses: actions/download-artifact@v7
        with:
          name: kernel-kit-output-usrmerge-${{ matrix.kversion }}.x-x86
          path: .
      - name: rename artifacts4
        run: for i in huge-* ; do mv $i ${{ matrix.kversion }}-x86-$i ; done
  release:
    runs-on: ubuntu-24.04
    needs: get-artifacts
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Puppy-Kernels-${{ matrix.kversion }}
          tag_name: Puppy-Kernels-${{ matrix.kversion }}/release-${{ steps.version.outputs.builddate }}
          fail_on_unmatched_files: true
          files: |
            *.tar.bz2
            *.txt
            kernel_sources*
