name: slackware-s15pup

on:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            compat-distro: slackware64
            compat-distro-version: s15pup64
            kernel: 5.15.x
          - arch: x86
            compat-distro: slackware
            compat-distro-version: s15pup32
            kernel: 5.10.x
    if: github.repository == 'puppylinux-woof-CE/woof-CE'
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      arch: ${{ matrix.arch }}
      compat-distro: ${{ matrix.compat-distro }}
      compat-distro-version: ${{ matrix.compat-distro-version }}
      kernel: ${{ matrix.kernel }}
      artifact: ${{ matrix.compat-distro }}-${{ matrix.compat-distro-version }}-${{ github.run_number }}
      retention: 30
