name: slackware-14.2

on:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            compat-distro: slackware64
          - arch: x86
            compat-distro: slackware
    if: github.repository == 'puppylinux-woof-CE/woof-CE'
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      arch: ${{ matrix.arch }}
      compat-distro: ${{ matrix.compat-distro }}
      compat-distro-version: 14.2
      kernel: 4.19.x
      artifact: ${{ matrix.compat-distro }}-14.2-${{ github.run_number }}
      retention: 30
      runner: 'ubuntu-20.04'
