name: slackware-14.2

on:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  build:
    if: github.repository == 'puppylinux-woof-CE/woof-CE'
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      arch: x86
      compat-distro: slackware
      compat-distro-version: 14.2
      kernel: 4.19.x
      artifact: ${{ github.workflow }}-${{ github.run_number }}
      retention: 30
