name: void-voidpup32

on:
  schedule:
    - cron: '0 0 2 * *'

jobs:
  build:
    if: github.repository == 'puppylinux-woof-CE/woof-CE'
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      arch: x86
      compat-distro: void
      compat-distro-version: voidpup32
      kernel: 5.10.x
      artifact: ${{ github.workflow }}-${{ github.run_number }}
      retention: 30
