#!/bin/sh
#Barry Kauler LGPL 2007
#called from /usr/sbin/modemtest
#the idea is to probe modem and determine a suitable hayes command init string.

[ ! -e /dev/modem ] && exit

#talk to modem, wait for response, kill if hung...
# $1: command
# $2: device
chat_with_modem() {
	local ANSWERFILE="/tmp/modemstatsret"
	local COMMAND=$1 DEVICE=$2 CNTLP=1
	rm -f $ANSWERFILE
	if [ "$(which modem-stats 2>/dev/null)" ];then
		#hangs if modem unplugged or turned off (contrary to what docs say)...
		modem-stats -c $COMMAND $DEVICE > $ANSWERFILE 2>/dev/null &
		local MSPID=$!
		while [ $CNTLP -le 7 ] ;do
			sleep 1
			busybox pidof modem-stats | grep -q -w "$MSPID" || break
			CNTLP=$(( $CNTLP + 1 ))
		done
		kill $MSPID 2>/dev/null
	elif [ "$(which microcom 2>/dev/null)" ];then
		if [ -f "/var/lock/LCK..${DEVICE##*/}" ] ; then
			rm -f "/var/lock/LCK..${DEVICE##*/}"
		fi
		echo -e "${COMMAND}\r" | microcom -t 1000 $DEVICE > $ANSWERFILE 2>/dev/null
	fi
	[ -s $ANSWERFILE ] && grep -q '^OK' $ANSWERFILE
	return $?
}

chat_with_modem 'ATZ' /dev/modem || exit

ALLSTR=""
for ONESTEP in 'Q0V1E1' 'Z' 'S0=0' '&C1' '&D2' 'S11=55' '+FCLASS=0'
do
	if ! chat_with_modem "AT$ONESTEP" /dev/modem ;then
		chat_with_modem 'ATZ' /dev/modem #maybe wise to reset modem.
		continue
	fi
	[ "$ONESTEP" = "Z" ] && continue
	ALLSTR="$ALLSTR$ONESTEP"
done

#NO, the problem with country codes is there does not seem to be one standard.
#the codes differ, also Hayes command for querying the current code differs,
#also some modems are hardwired for a particular country and will not accept
#any country code.
##country code...
SETCOUNTRY=""

#But, some firmware scripts in /etc/init.d/ do write a country string to
#/etc/countryinfo...
if [ -f /etc/countryinfo ];then
 . /etc/countryinfo
 if [ "$MODEM_COUNTRY_STRING" ];then
  SETCOUNTRY="`echo -n "$MODEM_COUNTRY_STRING" | sed -e 's/^AT/ /'`"
 fi
fi

echo -n "AT$ALLSTR$SETCOUNTRY" > /tmp/mymodeminitstring

###END###
